### ISSUE TITLE
App Design / Structure

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#100]
To date, we have encouraged quick iteration on features to allow for early API feedback. This ensured we understood how Marquez would collect metadata on running jobs as well as handle versioning of datasets (conversations that are still ongoing). Recently, our [data model](https://www.lucidchart.com/documents/view/f918ce01-9eb4-4900-b266-49935da271b8/0) has seen many additions (_namespaces!_). As a result, we need to address our current app structure. Mainly, this means decoupling the _DAO Layer_ from the _Resource Layer_ and introduce a _Service Layer_ to encapsulate all DAO interactions and allow each layer to evolve independently #66.

**Note:** App restructuring is required before opening up the project for contributions.
 
### App Design

The multi-layer app design will consist of: 

- **Resource Layer**
- **Service Layer**
- **DAO Layer**

See [Organizing Marquez Code](https://docs.google.com/document/d/17qrJNFx5YfFWiSNqd53lMed-YOfjTeZUhkis3rAGbN0/edit) doc for more details.

### App Structure

We'll also have the following project structure:

```
marquez/
├── api/
│   ├── exceptions
│   ├── mappers
│   ├── models
│   └── validation
├── core/
│   ├── exceptions
│   ├── mappers
│   ├── models
│   └── services
├── db
├── health
└── resources
```
* `api`:  Representations (i.e. request and response bodies).
** `api/exceptions`:  All registered custom [ExceptionMapper](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/ext/ExceptionMapper.html).
* `api/models`:  API models *not* including req/res bodies.
* `api/mappers`: Defines model [Mappers](https://github.com/MarquezProject/marquez/blob/update-app-structure/src/main/java/marquez/core/mappers/Mapper.java).
* `api/validation`: Validation of request and response bodies.
* `core`: Domain implementation; objects not used in the API.
* `core/exceptions`: Defines all runtime executions
* `core/mappers`: Provides data transformations across layers  
* `core/models`: Objects not used in the API 
* `core/services`: Service classes encapsulating all DAO interactions / logic #118 
* `db`: Database access classes; defines all [RowMappers](http://jdbi.org/#_row_mappers)
* `health`: Runtime health checks
* `resources`: Resources exposed in our RESTful API

**Comment by sshah-wework** [comment]
Nice 👍
