### ISSUE TITLE
UI displays nothing after choosing 'namespaces' filter 

### ISSUE THREAD

**Issue by AndriiSushko** [MarquezProject/marquez#1010]
### How to reproduce: 

1) Open Marquez home page, see available datasets:  
![1](https://user-images.githubusercontent.com/29128104/108972976-898ab500-768c-11eb-9631-8244479b11aa.png)

2) Chose 'namespaces' filter
![2](https://user-images.githubusercontent.com/29128104/108972977-8abbe200-768c-11eb-87a7-7f9f3c7bb7b1.png)

3) See 'no datasets found'/ 'no jobs found' (even though there are datasets and namespaces) 
![3](https://user-images.githubusercontent.com/29128104/108972979-8abbe200-768c-11eb-8fbb-dedcb57de28e.png)

### Environment: 
MacOS Big Sur 11.2.1
Google Chrome 88.0.4324.182 (Official Build) (x86_64) OR  Safari 14.0.3 (16610.4.3.1.4) 
Docker Engine v20.10.2
[marquez-docker-compose.yaml](https://github.com/MarquezProject/marquez/blob/main/docker-compose.yml)

### Other 
[Same issue in slack thread](https://marquezproject.slack.com/archives/C01E8MQGJP7/p1614106884008500)

**Comment by wslulciuc** [comment]
Thanks for opening this issue, @AndriiSushko We're working on ways to best filter dataset and job metadata. For now, we've removed the filters as we revisit / discuss the user experience for filter metadata. As an alternative, we suggest using the search bar in the UI. See https://github.com/MarquezProject/marquez/pull/1063

/cc @phixMe
