### ISSUE TITLE
Enable vulnerability docker image scanning with snyk

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1018]
Now that we've enabled [renovate](https://github.com/MarquezProject/marquez/pull/942) to keep libs up to date with latest bug / security patches, I'd be great to see if we can enable [snyk](https://snyk.io/test/github/MarquezProject/marquez) to scan our [publish images for Marquez](https://hub.docker.com/repositories) for security vulnerabilities.

**Comment by KevinMellott91** [comment]
@wslulciuc I signed up for a snyk account to play around, and was able to scan the Marquez images on Docker Hub. To do this, I went to Integrations --> Docker Hub and chose the two Marquez images. Is that something that is available when you log into snyk, or might I be seeing some sort of trial account functionality?

<img width="1134" alt="Screen Shot 2021-02-28 at 11 58 14 AM" src="https://user-images.githubusercontent.com/6477529/109428451-ce7c5780-79bc-11eb-96ea-93096975ec20.png">

**Comment by wslulciuc** [comment]
Thanks for your help on this, @KevinMellott91 👍. On our official snyk account for Marquez, I was able to link our DockerHub account:

<img width="1134" alt="Screen Shot 2021-03-15 at 5 16 47 PM" src="https://user-images.githubusercontent.com/1553185/111237401-3aacad00-85b2-11eb-8817-569bbfa34065.png">
