### ISSUE TITLE
API documentation update needed. SchemaLocation is a required field for Dataset creation

### ISSUE THREAD

**Issue by anandhusk** [MarquezProject/marquez#1023]
In the API doc schemaLocation is mention as a non-required field but in code, it's a required field.

![image](https://user-images.githubusercontent.com/38855393/109501158-3914bc80-7abd-11eb-9af8-f5dd7dfba7db.png)

[API doc](https://marquezproject.github.io/marquez/openapi.html#tag/Datasets/paths/~1namespaces~1{namespace}~1datasets~1{dataset}/put)

[Code](https://github.com/MarquezProject/marquez/blob/main/api/src/main/java/marquez/service/models/StreamMeta.java#L48})

**Comment by henneberger** [comment]
This one is a bit hard to communicate and it isn't very clear from the documentation. The schema location is required only if the type is "STREAM". If the type is "DB_TABLE" then it is not required.

**Comment by julienledem** [comment]
resolved by #1024
