### ISSUE TITLE
Migrate airflow integration to OpenLineage endpoint

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#1089]
# Current state
Currently the Marquez-Airflow integration uses the original Marquez API
https://github.com/MarquezProject/marquez/blob/main/integrations/airflow/marquez_airflow/dag.py#L162
This interaction is described here:
https://github.com/MarquezProject/marquez/blob/main/docs/run-lifecycle.md

We are now moving to sending OpenLineage events:
https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.md
Which consists of one start event and one end event.
Marquez has an OpenLineage endpoint here:
https://github.com/MarquezProject/marquez/blob/main/api/src/main/java/marquez/service/OpenLineageService.java

# Goal 
We want to migrate the marquez-airflow integration to the OpenLineage endpoint.
Moving forward it's going to be the only endpoint to collect metadata.

# References
For reference, the new spark integration is using this new OpenLineage endpoint:
https://github.com/MarquezProject/marquez/tree/main/integrations/spark
in particular:
A simple OpenLineage client (we’re working on adding this to the OpenLineage repo): https://github.com/MarquezProject/marquez/tree/main/integrations/spark/src/main/java/marquez/spark/agent/client
emitting events:
https://github.com/MarquezProject/marquez/blob/main/integrations/spark/src/main/java/marquez/spark/agent/lifecycle/SparkSQLExecutionContext.java

**Comment by mobuchowski** [comment]
Should the new client drop original Marquez client's backend concept? Spark's OpenLineage client does not support this.

**Comment by mobuchowski** [comment]
I'll assume supporting those would be in context of some future pull request.
