### ISSUE TITLE
Flaky Airflow integration test

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1093]
When running the Airflow integration test in CI, the test sometimes fails the assertion that `Dataset.lastModifiedAt` should be set:

```
integration_1        | [2021-03-16 16:55:47,018] {client.py:394} INFO - http://marquez:5000/api/v1/namespaces/food_delivery/datasets/public.popular_orders_day_of_week method=GET duration_ms=34
integration_1        | Traceback (most recent call last):
integration_1        |   File "integration.py", line 250, in <module>
integration_1        |     main()
integration_1        |   File "integration.py", line 244, in main
integration_1        |     check_datasets_meta()
integration_1        |   File "integration.py", line 160, in check_datasets_meta
integration_1        |     assert out_table['lastModifiedAt'] is not None
integration_1        | AssertionError
```

When triggering the failed CI job, it passes. For example,

* **Failed:** https://app.circleci.com/pipelines/github/MarquezProject/marquez/2031/workflows/0552b18e-99a0-49bf-b5b8-fb1ecd097a32
* **Successful:** https://app.circleci.com/pipelines/github/MarquezProject/marquez/2031/workflows/c211b1f1-4214-4e23-bc77-897775c70bdf/jobs/14883

**Comment by julienledem** [comment]
this has been resolved.
