### ISSUE TITLE
Add airflow-specific run facet

### ISSUE THREAD

**Issue by mobuchowski** [MarquezProject/marquez#1096]
Currently, some info passed by airflow integration does not fit into core facets of OpenLineage.
We should add specific facet to pass this info:

    step_metadata.context['airflow.operator'] = operator
    step_metadata.context['airflow.task_info'] = str(task.__dict__)
    
    # Add version info
    step_metadata.context['airflow.version'] = AIRFLOW_VERSION
    step_metadata.context['marquez_airflow.version'] = MARQUEZ_AIRFLOW_VERSION

**Comment by julienledem** [comment]
Yes, this is a great suggestion.
Could you propose a json-schema for it?
