### ISSUE TITLE
Add tags support for jobs and job runs

### ISSUE THREAD

**Issue by pwnage101** [MarquezProject/marquez#1100]
Jobs and job runs already do have arbitrary key/value dictionaries as properties (see job.context and run.args) but not all job or job run metadata might fit into those categories.  For example: 

* Job runs may be associated with a jenkins job build ID, but that information is not technically an argument.

**Comment by julienledem** [comment]
Now that we support OpenLineage, this should go into a Custom Job facet.
https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.md#facets
