### ISSUE TITLE
Improve Airflow local development

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1109]
Currently, you can only run the `marquez-airflow` [integration tests](https://github.com/MarquezProject/marquez/tree/main/integrations/airflow/tests/integration) via a PR or git sha. This requires you always open a PR when wanting to run an integration test. Let's update the test to also allow for installing the current _local_ development version of the library from source, improving the local development experience.

**Comment by mobuchowski** [comment]
Done in https://github.com/MarquezProject/marquez/pull/1135 and https://github.com/MarquezProject/marquez/pull/1142
