### ISSUE TITLE
Add OutputStatistics Facet to BigQuery integration in marquez-airflow

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#1144]
## Goal
Add an OutputStatistics facet (row count and byte size) to the output of the BigQuery job.
It reflects how many rows (and bytes) where written to the output for the job.

## For reference:
 - this information is available in the statistics outputs of the bigquery job: https://github.com/MarquezProject/marquez/blob/8fe6f6205a9833cffdc62537fd1c61150efdc443/integrations/airflow/tests/extractors/job_details.json
- In particular: 
statistics.query.queryPlan: https://github.com/MarquezProject/marquez/blob/8fe6f6205a9833cffdc62537fd1c61150efdc443/integrations/airflow/tests/extractors/job_details.json#L34

For the last operator in the plan (The output)
https://github.com/MarquezProject/marquez/blob/8fe6f6205a9833cffdc62537fd1c61150efdc443/integrations/airflow/tests/extractors/job_details.json#L179
```
               "recordsRead": "20",
               "recordsWritten": "20",
```

 - OutputStatistics facet in the spark integration: https://github.com/MarquezProject/marquez/blob/main/integrations/spark/src/main/java/marquez/spark/agent/facets/OutputStatisticsFacet.java

**Comment by mobuchowski** [comment]
https://github.com/MarquezProject/marquez/pull/1196
