### ISSUE TITLE
Add support for the SnowflakeOperator to the marquez-airflow integration

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#1161]
# Goal:
Add lineage coverage for the [Snowflake Operator](https://github.com/apache/airflow/blob/v1-10-stable/airflow/contrib/operators/snowflake_operator.py)
This is done by adding a SnowflakeExtractor

# Reference:
This should work like the [PosgresExtractor](https://github.com/MarquezProject/marquez/blob/main/integrations/airflow/marquez_airflow/extractors/postgres_extractor.py)

**Comment by mobuchowski** [comment]
Done in https://github.com/MarquezProject/marquez/pull/1270
