### ISSUE TITLE
v0.1.0 Service Layer Methods

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#118]
# Marquez 0.1.0

| Key                 | Description |
| ---------------------- | ------------ |
|+ | Public |
|- | Private |

## NamespaceService

| Method               | Throws | Description |
| --- | --- | --- |
| + `Namespace create(String name)` | NamespaceException | Creates a namespace. |

## JobService

| Method                 | Description |
| ---------------------- | ------------ |
| + `Job create(namespace, Job)`        | |
| - `JobVersion createVersion(namespace, Job)` | |
| + `Job[] getAll(namespace)`             | |
| + `JobVersion[] getAllVersions(namespace, jobName)`        | |
| + `JobVersion getVersionLatest(namespace, jobName)`   | |

## DatasetService

| Method               | Description |
| -------------------- | ------------ |
| + `JobRun createJobRunOutputs(namespace, jobName, runId, Dataset[])` | |
| - `DatasetVersion createVersion(namespace, Dataset)` | |
| + `Dataset[] getAll(namespace)` | |

**Comment by wslulciuc** [comment]
@sshah-wework : Great idea to capture the services and their respective contracts needed for #100. We'll want to flush out more of the details around functionality for each service and make sure we update this issue accordingly.
