### ISSUE TITLE
Publish Java Client to Maven Central

### ISSUE THREAD

**Issue by KevinMellott91** [MarquezProject/marquez#1194]
When releasing new versions of Marquez, can we start deploying the [Java Client](https://github.com/MarquezProject/marquez/tree/main/clients/java) to Maven Central? The [most recent version](https://search.maven.org/search?q=a:marquez-java) is currently 1.4.1-rc.6.

Happy to help with this if there is a release script to be modified; please just point me in the right direction.

**Comment by wslulciuc** [comment]
Version ` 1.4.1-rc.6` was published by mistake :( We align the release of the java client with the release of Marquez, which is currently [`0.13.1`](https://github.com/MarquezProject/marquez/releases/tag/0.13.1)

**Comment by KevinMellott91** [comment]
Thank you @wslulciuc , I was getting fooled by the "latest version" indicator in Maven Central, but now I see that the Marquez clients have been getting published regularly. Your explanation about the mistaken version number makes sense, as it appears Maven Central considers "latest" based on version number, rather than publish date.

![Screen Shot 2021-04-09 at 12 41 12 PM](https://user-images.githubusercontent.com/6477529/114220070-22217f80-9931-11eb-87f0-c90fde04ea33.png)

![Screen Shot 2021-04-09 at 12 43 29 PM](https://user-images.githubusercontent.com/6477529/114220121-34032280-9931-11eb-8072-375ea436556b.png)

**Comment by wslulciuc** [comment]
@KevinMellott91: Yeah, a bit frustrating TBH. But, Marquez will soon have a `1.0.0` release that will, eventually, override my mistake :/
