### ISSUE TITLE
List job runs

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#121]
Let's support listing job runs. We'll want to update the OpenAPI spec accordingly #100 #104 

**GET** /namespaces/`:namespace`/jobs
```bash
{
  "name": "my_first_job",
  "description": "Best job ever!",
  ...
  "runs": [
    "/jobs/runs/cfc4b5e6-c630-48d4-ad19-f2bd16c93a9d",
    "/jobs/runs/d33ef190-73bd-4a65-ab59-1bbd65364d0b",
    "/jobs/runs/5ced1097-8d59-46d8-933e-c9a688be8b8c",
    ...
  ]
}
```

We may want to list job runs when fetching a job by name. The endpoint above is not yet finalized, and something we can iterate on (just wanted to capture the functionality).

**Comment by wslulciuc** [comment]
/ cc @Liorba

**Comment by ashulmanWeWork** [comment]
This is a good way to define these resources -- I was thinking to tweak it as such:

```/namespaces/:namespace/jobs``` --> lists the jobs currently in that namespace.
```/namespaces/:namespace/job_runs``` --> lists the job runs currently in that namespace.
This will likely be implemented as part of the namespace resource, but the service functions that we need, namely `JobService.getAllJobsInNamespace()`, are in the `JobService`, and will require adding that dependency to the `NamespaceResource`. It's doable, but I started to wonder if we could do it differently.

A design alternative that came to mind was to add a parameter to the `/api/v1/jobs/runs/` endpoint, called `namespace` that would filter the runs by the namespace and achieve the same result.

Thoughts? :)

**Comment by wslulciuc** [comment]
It might help to highlight the question we are looking to answer:

> Given job K, return a list L of runs for K

So, let's say I have the job `my_job` under the namespace `my_namespace`. The API call:

```
GET namespaces/my_namespace/jobs/my_job/runs
```

will return the list of runs for `my_job`. Cool. Now, maybe I'm only interested in failed run attempts, we can and should add the filter `run_state` to limited our results:

```
GET namespaces/my_namespace/jobs/my_job/runs?run_state=FAILED
```

Note that the `jobs/runs/*` endpoints were introduced to simplify interactions with a single job run instance, not a global list.

But, now let's say we wanted to view runs for multiple jobs: `my_job`, `my_other_job`, then that would require following the steps outlined above for each job.

The issue does outline (possible) returning a list of runs when retrieving a job:
```
  ...
  "runs": [
    "/jobs/runs/cfc4b5e6-c630-48d4-ad19-f2bd16c93a9d",
    "/jobs/runs/d33ef190-73bd-4a65-ab59-1bbd65364d0b",
    "/jobs/runs/5ced1097-8d59-46d8-933e-c9a688be8b8c",
    ...
  ]
```

My thinking here is that it's more of an optimization for the caller. Maybe we return the last `N` completed runs or something similar, but not a feature we'd need to support in release `0.2.0`.

**Comment by wslulciuc** [comment]
continued: I think it would be fine to define the endpoint:

```
GET /jobs/runs
```
returning a list of run IDs. But to learn more about the job run, the caller would have to make the API call:


```
GET /jobs/runs/cfc4b5e6-c630-48d4-ad19-f2bd16c93a9d
```

**Comment by ashulmanWeWork** [comment]
I like the idea of calling `GET /jobs/runs`, and then potentially filtering by namespace or by namespace and job_name. For example, to find all the jobs runs for namespace `finance`:
`GET /api/v1/jobs/runs?namespace=finance`
To find info about any runs for a given job, say `quarterly_billings`, which resides in the `finance` namespace, we would do this:
`GET /api/v1/jobs/runs?namespace=finance?job_name=quarterly_billings`.

Does this sound like a sensible way to proceed?

**Comment by sshah-wework** [comment]
Chiming in here, would rather see

```
GET namespaces/{namespace}/jobs/{job}/runs
```

Than 
```
/jobs/runs?namespace=...&job=
``` 

since the first is more canonical. the `/jobs/runs` endpoint was just meant to be convenient for fetching a single run by ID, but I'd rather not support more functionality from that endpoint.

One day, we may want the equivalent lookup via a `id` filter (e.g. `GET namespaces/{namespace}/jobs/{job}/runs?id=...`) for consistency.

**Comment by wslulciuc** [comment]
Being added in #633
