### ISSUE TITLE
Airflow example doesn't work out of the box.

### ISSUE THREAD

**Issue by lewiesnyder** [MarquezProject/marquez#1217]
I ran into an issue with [step 5](https://github.com/MarquezProject/marquez/tree/main/examples/airflow#step-5-troubleshoot-a-failing-dag-with-marquez) (troubleshooting an upstream change) of the airflow example.

counter.py should have the following changes to be able to be fully resolved:
t1:
```python
    sql='''
    DO $$
    BEGIN
      IF EXISTS(SELECT *
        FROM information_schema.columns
        WHERE table_name='counts' and column_name='value')
      THEN
          ALTER TABLE "counts" RENAME COLUMN "value" TO "value_1_to_10";
      END IF;
    END $$;
    ''',
```

t2:
```python
    sql='''
    INSERT INTO counts (value_1_to_10)
         VALUES (%(value)s)
    ''',
```

**Comment by wslulciuc** [comment]
Thanks @lewiesnyder for giving the example a try! Mind opening a PR with your suggestions to fix the example?

**Comment by wslulciuc** [comment]
FYI, the Airflow example would still work with the current query, but, I agree, the way the upstream table schema is modified could be a bit cleaner.
