### ISSUE TITLE
Enable junit5

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1226]
When we merged the junit5 upgrade PR (#1195) the tests for the `api` and `java` client stoped running. That is:

* Here's CI before the junit5 merge: https://app.circleci.com/pipelines/github/MarquezProject/marquez/2533/workflows/0e92d31a-e803-47d5-8129-c3c56789204e/jobs/18155
* Then after the merge: https://app.circleci.com/pipelines/github/MarquezProject/marquez/2546/workflows/cf0ae259-3f38-4bf2-b275-3166e893e15a/jobs/18249

To enable junit5 to run (not enabled by default in gradle), we first need to add the following to the root [`build.gradle`](https://github.com/MarquezProject/marquez/blob/main/build.gradle) file:

```
tests {
  useJUnitPlatform()
}
```

Once enabled, you can run `./gradlew build` from the project root and you'll notice that some tests are now failing.

**Comment by mobuchowski** [comment]
Turns out that problem with flaky tests was caused by lack of isolation between integration test classes - they shared the same postgres instance. Now, database is isolated on class level in https://github.com/MarquezProject/marquez/pull/1227
