### ISSUE TITLE
Add `currentVersion` to Dataset and Job models

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1283]
Let's add `currentVersion` to the Dataset and Job models returned by the API. The `currentVersion` field would be a pointer to the current version for a given dataset or job. For example, let's say we have a dataset with the `currentVersion` set to `b1d626a2-6d3a-475e-9ecf-943176d4a8c6`, we can use the DatasetVersion API to retrieve that version:

## `GET` `/api/v1/namespaces/my-namespace/datasets/my-dataset/versions/b1d626a2-6d3a-475e-9ecf-943176d4a8c6`

```
{
  "id": {
    "namespace": "my-namespace",
    "name": "my-dataset"
  },
  "type": "DB_TABLE",
  "name": "my-dataset",
  "physicalName": "public.mytable",
  "createdAt": "2019-05-09T19:49:24.201Z",
  "version": "b1d626a2-6d3a-475e-9ecf-943176d4a8c6",
  "namespace": "my-namespace",
  "sourceName": "my-source",
  "fields": [
    {"name": "a", "type": "INTEGER","tags": []},
    { "name": "b","type": "TIMESTAMP","tags": []},
    {"name": "c", "type": "INTEGER","tags": []},
    {"name": "d", "type": "INTEGER","tags": []}
  ],
  "tags": [],
  "description": "My first dataset!",
  "createdByRun": {
    "id": "0e89b60a-d80d-42ae-a12b-bd79ae1fb576",
    "createdAt": "2019-05-09T18:52:35.620763Z",
    "updatedAt": "2019-05-09T18:53:41.461122Z",
    "nominalStartTime": null,
    "nominalEndTime": null,
    "state": "COMPLETED",
    "startedAt": "2021-02-05T18:53:33.245492Z",
    "endedAt": "2021-02-05T18:53:41.461122Z",
    "durationMs": 8216,
    "args": {
      "email": "me@example.com",
      "emailOnFailure": false,
      "emailOnRetry": true,
      "retries": 1
    }
  }
}
```

**Comment by OleksandrDvornik** [comment]
@wslulciuc do we want to have `currentVersion` field in client also or just return from API?

**Comment by wslulciuc** [comment]
> do we want to have currentVersion field in client also or just return from API?

Yeah, we'll want the OpenAPI spec, clients, etc updates with the new field.
