### ISSUE TITLE
Add job version endpoint to the API

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#130]

**Comment by wslulciuc** [comment]
@sshah-wework mind adding more details about the feature request?

**Comment by sshah-wework** [comment]
sure, this was for direct job version management. so get / create / delete (probably no update) of a job version, given a job.

**Comment by wslulciuc** [comment]
Thanks! Now I remember. This was to allow for the caller to manage job versioning rather than Marquez implicitly .

**Comment by nkijak** [comment]
There doesn't seem to be a job version endpoint at the moment. Is this more of a planning thing, as in "describe the ideal job version endpoint"?

**Comment by sshah-wework** [comment]
This issue has aged a bit. But the background is: for simplicity, the initial approach was to allow Marquez to manage job versions implicitly and not expose them externally since job versions were less critical to expose than jobs and job runs. The thinking at one point was to expose job versions for visualization and enabling other features in the UI.

**Comment by julienledem** [comment]
Duplicate, see https://github.com/MarquezProject/marquez/issues/614
