### ISSUE TITLE
Ensure airflow integration follow the open lineage naming convention for datasets

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#1363]
We need to go over the integrations (postgres, bigquery, snowflake, redshift, GE) and make sure that the Inputs and outputs follow this convention.
https://github.com/OpenLineage/OpenLineage/blob/main/spec/Naming.md
In particular, the namespace

**Comment by mobuchowski** [comment]
https://github.com/MarquezProject/marquez/pull/1453
