### ISSUE TITLE
Marquez spark integration `producer` field does not reflect current version

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#1365]
See value of the constant does not match the tag.
We should dynamically populate this from build metadata.
https://github.com/MarquezProject/marquez/blob/0.13.1/integrations/spark/src/main/java/marquez/spark/agent/client/OpenLineageClient.java#L35

See Marquez java client

**Comment by mobuchowski** [comment]
https://github.com/MarquezProject/marquez/pull/1373
