### ISSUE TITLE
Marquez Java Client DatasetVersion and DbTableVersion models missing 'facets' field

### ISSUE THREAD

**Issue by dominiquetipton** [MarquezProject/marquez#1380]
The Marquez Java Client [DatasetVersion](https://github.com/MarquezProject/marquez/blob/485897226a32824c6e4f4787b2250d1a7de8c819/clients/java/src/main/java/marquez/client/models/DatasetVersion.java#L55) and [DbTableVersion](https://github.com/MarquezProject/marquez/blob/485897226a32824c6e4f4787b2250d1a7de8c819/clients/java/src/main/java/marquez/client/models/DbTableVersion.java#L39) models are missing the `facets` field unlike the regular [Dataset](https://github.com/MarquezProject/marquez/blob/485897226a32824c6e4f4787b2250d1a7de8c819/clients/java/src/main/java/marquez/client/models/Dataset.java#L58) and [DbTable](https://github.com/MarquezProject/marquez/blob/485897226a32824c6e4f4787b2250d1a7de8c819/clients/java/src/main/java/marquez/client/models/DbTable.java#L42) and the API [DatasetVersion](https://github.com/MarquezProject/marquez/blob/485897226a32824c6e4f4787b2250d1a7de8c819/api/src/main/java/marquez/service/models/DatasetVersion.java#L65) and [DbTableVersion](https://github.com/MarquezProject/marquez/blob/485897226a32824c6e4f4787b2250d1a7de8c819/api/src/main/java/marquez/service/models/DbTableVersion.java#L47).

**Comment by wslulciuc** [comment]
Thanks for pointing this out, @dominiquetipton! We'll fix this issue in our `0.16.0` release.

**Comment by dominiquetipton** [comment]
Always glad to help, thanks! :)

**Comment by wslulciuc** [comment]
@dominiquetipton Did you want to add the missing fields? Happy to assign this to you!

**Comment by dominiquetipton** [comment]
Sounds good to me 👍

**Comment by wslulciuc** [comment]
Great! Let us know if you need any help. Also, checkout our [CONTRIBUTING.md](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md) with steps on how to contribute to Marquez.
