### ISSUE TITLE
Fix test failures in DatasetSerializationTest

### ISSUE THREAD

**Issue by ashulmanWeWork** [MarquezProject/marquez#140]
These tests started failing in the past couple weeks when run locally, though oddly enough did not fail when run against CircleCI.

**Comment by ashulmanWeWork** [comment]
This is related to daylight savings time. The issue is that UTC does not account for daylight savings time, whereas the Java TZ object does.

I have a simple test fix that works locally that corrects this imbalance. Hope to get this up shortly.

That said, it doesn't explain why in CircleCI these tests pass. If they were to fail, they should have started to fail after November 4th. Could it be that time settings/standards are different on the build machine than local machines?

**Comment by sshah-wework** [comment]
Yes, CircleCI machine are probably also using UTC time. Ideally, this test should not use the local time zone and always assume UTC.
