### ISSUE TITLE
Upserting tags doesn't update tag

### ISSUE THREAD

**Issue by hanbei** [MarquezProject/marquez#1412]
The method `upsertTag` in [TagDao](https://github.com/MarquezProject/marquez/blob/009c865b141e71c2ab07f6d0a167a13e44890bea/api/src/main/java/marquez/db/TagDao.java) doesn't really update the tag description. The tag may be created but may never be changed afterwards.

**Comment by wslulciuc** [comment]
@hanbei Did you want to fix this issue?

**Comment by hanbei** [comment]
Special care should be taken handling `null` description values. The `upsert` method branches depending on the nullability of the description: 
https://github.com/MarquezProject/marquez/blob/009c865b141e71c2ab07f6d0a167a13e44890bea/api/src/main/java/marquez/db/TagDao.java#L44-L52

Should it be possible to overwrite tag descriptions with `null` or only with proper strings? Should we check for empty strings and handle them the same as null values?

**Comment by hanbei** [comment]
@wslulciuc I can try. SQL is not my strong suite. But I have an idea and some tests :)

**Comment by wslulciuc** [comment]
> Should it be possible to overwrite tag descriptions with null or only with proper strings? Should we check for empty strings and handle them the same as null values?

For Marquez, we'll be moving towards a convention where `nulls` represent the absence of a field. For example, in the case of job inputs / outputs, when set to `null` the inputs / outputs are **not** known, while the empty set `[]` means that they **are** known for the job but are empty.

As for the tag descriptions, you shouldn't be able to override the with `null`, but an empty string would be valid.
