### ISSUE TITLE
Promote the lineage API out of beta

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#1416]
currently the lineage api is on /api/v1-beta/lineage
See:
https://github.com/MarquezProject/marquez/blob/main/api/src/main/java/marquez/api/LineageResource.java
It is time to promote it to /api/v1/lineage

Possibly adding GET methods here.
https://github.com/MarquezProject/marquez/blob/main/api/src/main/java/marquez/api/OpenLineageResource.java

The old path should work for the duration of the deprecation cycle

**Comment by wslulciuc** [comment]
Fixed #1457
