### ISSUE TITLE
UI search is 'sticky'

### ISSUE THREAD

**Issue by krehermann** [MarquezProject/marquez#1521]
Search does not work when the context of the UI is in a job or dataset

LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Tested with Brave, Chrome, Firefox

Reproduce by 
go to http://localhost:3000/
search for something (works)
click on job or dataset
search for something else -- nothing happens

Need to X out of the dataset/job in the bottom panel to recover search ability

![marquez_ubuntu_sticky_search](https://user-images.githubusercontent.com/16602512/125537611-7a325f17-aa8c-4f03-a942-b39387b5e3bb.png)

**Comment by wslulciuc** [comment]
Thanks for opening this is, @krehermann! We've been working on developing the backend API for Marquez, but will be soon prioritizing UI bugs as well. I've added this issue to release `0.17.0`
