### ISSUE TITLE
Spark integration needs to parse JDBC Relation queries

### ISSUE THREAD

**Issue by collado-mike** [MarquezProject/marquez#1524]
A Spark JDBCRelation can be defined a SQL statement, rather than a reference to a single table- see the docs at- https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html (the `query` configuration key). 

This is referenced in the JDBCRelation handler at https://github.com/MarquezProject/marquez/blob/main/integrations/spark/src/main/java/marquez/spark/agent/lifecycle/plan/LogicalRelationVisitor.java#L116-L118

**Comment by wslulciuc** [comment]
The spark integration has been moved to `OpenLineage` #1585
