### ISSUE TITLE
Codegen errors with openapi.yml

### ISSUE THREAD

**Issue by krehermann** [MarquezProject/marquez#1538]
Hi,

I'm playing around with generating golang bindings from the spec file.

This uncovered a few problems, which I think are typos/bugs in the spec.

I'm using https://github.com/deepmap/oapi-codegen for the code gen. It's possible that the error lies there; I'm not terribly familiar openapi.

Nevertheless a close scrunity of the errors leads me to believe there are 3 illegal syntax errors in the current spec
- 2 parameters instead of one for /namespaces/{namespace}/datasets
- Unknown 'required' field in 'schema' object, which I think is an indentation typo
- Unknown type 'enum'. I think was intended to be a string.

This diff enables code gen to succeed and addresses the three issues in order

```
diff --git a/spec/openapi.yml b/spec/openapi.yml
index d4c6f9e1..4cea6990 100644
--- a/spec/openapi.yml
+++ b/spec/openapi.yml
@@ -191,7 +191,6 @@ paths:
   /namespaces/{namespace}/datasets:
     parameters:
       - $ref: '#/components/parameters/namespace'
-      - $ref: '#/components/parameters/dataset'
     get:
       parameters:
         - $ref: '#/components/parameters/limit'
@@ -642,12 +641,13 @@ components:
     depth:
       name: depth
       in: query
+      required: false
       schema:
         type: integer
         example: 50
         default: 20
         description: The maximum number of edges from node.
-        required: false
+
 
   schemas:
     newNamespace:
@@ -1885,7 +1885,7 @@ components:
           type: string
           description: The ID of the node.
         type:
-          type: enum
+          type: string
           description: The type of the node.
           enum: [ DATASET, JOB ]
         data:
```

I see that @collado-mike has an open branch for refactoring the spec. If I have diagnosed these problems correctly, can they be absorbed there? Or would you prefer that I make an independent pull request for this?

**Comment by wslulciuc** [comment]
@krehermann Yeah, I'd prefer we merge #1537, then contribute your changes to the spec. Also, thanks for given the codegen option try! We've actually been dicussing using the openAPI spec to generate the models for both the core API and clients, so perfect timing!

**Comment by collado-mike** [comment]
I think the exact problems you call out are already in that branch. Hopefully, this addresses the golang approach, though I haven't tested that lang or the generator you're using.

**Comment by krehermann** [comment]
Fantastic @wslulciuc , @collado-mike.  I will wait. 

As a side note, the generated code does not compile for similiarly minor reasons -- 

Namespace, Source, and Tag are both objects and strings in the spec. This causes a type re-declaration error when compiling against the generated code.

While you are in the area and actively working on this, I would love if you invent a naming convention that address this ambiguity.
