### ISSUE TITLE
Support unknown types for Fields

### ISSUE THREAD

**Issue by collado-mike** [MarquezProject/marquez#1552]
In some cases, we can't determine the type of some fields in certain datasets. We should support the ability to report a field even if we can't determine its type.

**Comment by KevinMellott91** [comment]
@collado-mike are you envisioning the removal of dataset field type checking (similar to what was done with source types)? We are having a similar issue when publishing various database column types via the OL endpoint, when those types are not recognized by Marquez (ex: decimal vs decimal(10,2)).

**Comment by mobuchowski** [comment]
@KevinMellott91 was this fixed by https://github.com/MarquezProject/marquez/pull/1559 ?

**Comment by collado-mike** [comment]
> @collado-mike are you envisioning the removal of dataset field type checking (similar to what was done with source types)?
Yeah, we are having that discussion- there's some value in doing some type resolving (e.g., prevent a distinction between `int` `INT` and `INTEGER`), but overall, we are losing precision in the types by forcing the enum. One approach was done in https://github.com/MarquezProject/marquez/pull/1559 , but we're considering simply eliminating the enum and using another strategy for resolving the types.

**Comment by collado-mike** [comment]
Follow up in https://github.com/MarquezProject/marquez/issues/1560
