### ISSUE TITLE
 How can deployed marquez manually，not use docker.

### ISSUE THREAD

**Issue by oneanime** [MarquezProject/marquez#1558]
How can deployed marquez manually，not use docker.
after build this project ,I would not find **.tar.gz or software packages

**Comment by AvianshKumar** [comment]
@OleksandrDvornik 
What is ${MARQUEZ_CONFIG} in a java command? How to create this MARQUEZ_CONFIG file. Please help on that and please suggest how to deploy Marquez UI in Linux RHEL 7.4 server without docker.

**Comment by OleksandrDvornik** [comment]
Hi @AvianshKumar, `MARQUEZ_CONFIG` is a path to the marquez config yml 
`java -jar marquez-api.jar marquez.yml`

More details [here](https://github.com/MarquezProject/marquez/blob/main/README.md#configuration)

**Comment by AvianshKumar** [comment]
@OleksandrDvornik  Thanks for the quick response. you have any idea about installing of  Marquez UI in Linux RHEL 7.4 server without docker.

**Comment by OleksandrDvornik** [comment]
Basically you can take a look at how docker starts up for `web` module
You are interested in two bellow files.
```
https://github.com/MarquezProject/marquez/blob/main/web/Dockerfile
https://github.com/MarquezProject/marquez/blob/main/web/docker/entrypoint.sh
```
Basically, you should do:
1. Checkout Marquez project, go to the `web` folder and build it (npm install && npm run build )
2. Specify env variables (depends on our env):  
      - MARQUEZ_HOST=localhost
      - MARQUEZ_PORT=5000
3. Call `node setupProxy.js`
4. Check that it's up at `http://localhost:3000/`
Env variables are used in hitting an api url
`target: `http://${process.env.MARQUEZ_HOST}:${process.env.MARQUEZ_PORT}/``

**Comment by AvianshKumar** [comment]
Greate Thanks !!!

**Comment by wslulciuc** [comment]
@AvianshKumar: closing, but please reopen if you still need any guidance.
