### ISSUE TITLE
port 5000 is no longer available for use in macOS Monterey

### ISSUE THREAD

**Issue by rossturk** [MarquezProject/marquez#1572]
There is a new Airplay sharing feature in macOS Monterey that occupies ports 5000 and 7000:
https://developer.apple.com/forums/thread/682332

This prevents Marquez from starting without changing the port number - using the `docker/up.sh` method, this requires changes in multiple places.

**Comment by wslulciuc** [comment]
Thanks for opening this issue, @rossturk. We wouldn't be able to change the backend port, but the `docker/up.sh` script can provide an option for overriding the api and web ports. For example:

```bash
$ ./docker/up.sh  --api-port <api-port> --web-port <web-port>
```
