### ISSUE TITLE
Add Powered By section

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1581]
Let's add a _Powered By_ section in [`README.md`](https://github.com/MarquezProject/marquez/blob/main/README.md) 🚀 . Please add your organization below if you're collecting metadata with Marquez and you’d love to tell the world!

**Comment by KevinMellott91** [comment]
@wslulciuc Northwestern Mutual ✅

**Comment by wslulciuc** [comment]
Datakin ✅

**Comment by rossturk** [comment]
Astronomer 🚀
