### ISSUE TITLE
Standardize on the schema naming of human-readable names (e.g. owner vs. ownerName)

### ISSUE THREAD

**Issue by ashulmanWeWork** [MarquezProject/marquez#166]
To avoid ambiguity between describing an object vs. describing a primitive attribute about the object (e.g. a job json object vs. a job id or job name), we could potentially add more info into the attribute name. So for a string that represents the owner, (e.g. `mike_smith`), we'd have the field labeled as `ownerName` vs. `owner`

Wanted to get the pros and the cons of doing this and get a record of what we decide and why.

**Comment by wslulciuc** [comment]
We have decided on, in the example above, going with `ownerName`.
