### ISSUE TITLE
Ability to DELETE jobs and datasets

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#1736]
When jobs or datasets are deleted (or renamed) we need a way to tell Marquez that they don't exist anymore so that they don't clutter the lineage view.
It would make sense to have `DELETE` support on `/api/v1/namespaces/{ns}/datasets/{name}` and `/api/v1/namespaces/{ns}/jobs/{name}` resources.
This is a soft delete in the internal marquez model. It creates a new `deleted` version. The resources will not show up in the "current" lineage view in `GET /api/v1/lineage`

**Comment by julienledem** [comment]
also see #754

**Comment by mobuchowski** [comment]
Done in https://github.com/MarquezProject/marquez/pull/2032
