### ISSUE TITLE
Proposal: Add `emit` API to the Marquez client which accepts OpenLineage.RunEvent.

### ISSUE THREAD

**Issue by fm100** [MarquezProject/marquez#1741]
Related: #1686 

### Summary
PR #1717 deprecated write only clients in favor of using OpenLineage, and we want to have clear client experiences between Marquez and OpenLineage. Users are able to use OpenLineage client for even emission and use Marquez client for querying metadata, but it would be nice if Marquez client provides emit API which accepts `OpenLineage.RunEvent`. With this, users do not need to depend on two different clients but it still provides clear experiences.

### Proposal
Here I propose to add following API
Java:
```
public void emit(RunEvent event);
```

Python:
```
def emit(event: RunEvent) -> None:
```

**Comment by collado-mike** [comment]
My worry here is that it would be confusing to users. People would wonder whether they should use the OL client or the Marquez client. Especially since the off-the-shelf OL client doesn't actually have an HTTP backend implementation.  People could even build an OpenLineage integration using the Marquez client 🤦🏽‍♂️.

I could see an API that returned a new instance of the OpenLineage client for the sake of publishing an event- maybe something like 

```java
public io.openlineage.client.OpenLineage newOpenLineage(URI producer);
```
which would allow them to start publishing the event using a pre-configured OpenLineage client complete with a HTTP backend impl that has the Marquez server's `/lineage` endpoint configured as the target. Of course, this requires building such an impl in the OpenLineage client...

**Comment by mobuchowski** [comment]
>With this, users do not need to depend on two different clients but it still provides clear experiences.

At the beginning it sounded like a good idea - simpler interface.

Now I think that actually situations when one application both emits lineage events, and query or manipulate them is rather rare, and that separation might be actually a feature. Is there concrete use case to do this?

**Comment by fm100** [comment]
> > With this, users do not need to depend on two different clients but it still provides clear experiences.
> 
> At the beginning it sounded like a good idea - simpler interface.
> 
> Now I think that actually situations when one application both emits lineage events, and query or manipulate them is rather rare, and that separation might be actually a feature. Is there concrete use case to do this?

This kind of thing is actually what I wanted to hear, including @collado-mike 's comment above. Initial idea is to provide symmetric experiences to the users where consumption and production happens with the same client, but as you mentioned, the separation might be the feature we pursue.

I still see a bit of value for providing `emit` API or factory method for OpenLineage client, particularly for the users new to this area. They may find OpenLineage first and choose Marquez as a backend, or find Marquez first and get to know about OpenLineage. For the second case, it would be easier to onboard working with Marquez.

However, primary use cases are using OpenLineage integrations such as airflow and spark, and in those cases separation is very clear. Users don't need to write code for metadata collection and this separation is totally valid.

However, again, I think people's mind intuitively expect some symmetry, something like open/close, read/write pair. I had a verbal discussion about this @wslulciuc and would like to use this issue for the discussion. We might end up doing nothing and just close the issue, but it's worth having conclusion.

**Comment by fm100** [comment]
Had an offline discussion with @collado-mike and @wslulciuc and leaving update here. We already have bunch of PRs for deprecating create APIs from Marquez, and having another API for OpenLineage from marquez side sounds weird, because it already implements the OpenLineage spec. We decided to update the README of Marquez client to make it clear that using OpenLineage client is preferred way to collect metadata.

**Comment by fm100** [comment]
Closing this issue and will use #1686 for an update.
