### ISSUE TITLE
Your thoughts on Spline and possible collaboration?

### ISSUE THREAD

**Issue by wajda** [MarquezProject/marquez#1743]
Hi team,

I'm an a author and a team lead of an open-source data lineage tracking tool called Spline - https://github.com/AbsaOSS/spline maintained by AbsaOSS. I have recently learned about OpenLineage initiative and Marquez and it appeared to me (at least at the first glance) that both our project have a very lot in common. So I was wondering if you guys have seen Spline before and if it make sense for us to discuss the possibility to combine our efforts and create a product that would combine ideas and features from both projects?

**Comment by julienledem** [comment]
Hello Wajda,
We're very happy to collaborate. What did you have in mind?

**Comment by julienledem** [comment]
I can think of a few areas. Like Spline producing or consuming OpenLineage events. What else would be possible?

**Comment by wslulciuc** [comment]
@wajda, a bit late to the game but just wanted to say it's amazing to see spline support for OpenLineage! ❤️

**Comment by wajda** [comment]
@wslulciuc, thank you. Can you maybe mention Spline in the list of OpenLineage related projects or integrations?
