### ISSUE TITLE
Add timeout to wait-for-db.sh

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#176]
Let's add an optional `timeout` param (with a reasonable default) to specify the time limit (in seconds) to establish a DB connection:

```
./wait-for-db.sh <host> <port> [timeout]
```

**Comment by ajaymuppuri** [comment]
https://github.com/MarquezProject/marquez/pull/626

**Comment by ajaymuppuri** [comment]
Please review

**Comment by wslulciuc** [comment]
Fixed #626
