### ISSUE TITLE
UnexpectedException should extend RuntimeException

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#178]
UnexpectedException currently extends Throwable -- it will not behave the way want it (since it's not actually a subclass of Exception). We'll want it to behave like other RuntimeExceptions.

References:
- https://docs.oracle.com/javase/tutorial/essential/exceptions/throwing.html
- https://www.baeldung.com/java-new-custom-exception

**Comment by wslulciuc** [comment]
Fixed #304
