### ISSUE TITLE
Support data kinship between column and column?

### ISSUE THREAD

**Issue by melin** [MarquezProject/marquez#1792]
Support data kinship between columns and columns？

**Comment by alanmcruickshank** [comment]
@wslulciuc now the proposal has been accepted what would need to happen for column lineage relationships to be presented in the Marquez UI? [assuming that users stick to the proposed OL format for it]

**Comment by pawel-big-lebowski** [comment]
@alanmcruickshank We're working currently with column level lineage and Marquez API. UI part is still not started but progress can be tracked here: https://github.com/MarquezProject/marquez/labels/column-level-lineage

**Comment by pawel-big-lebowski** [comment]
Many column lineage features are already enabled, other are split to separate tasks. Closing this issue.
