### ISSUE TITLE
Marquez web container request timeout

### ISSUE THREAD

**Issue by TohnJhomas** [MarquezProject/marquez#1829]
The request being made by the Marquez UI container to the API container in order to fetch datasets is timing out with over 500 datasets. 

The web pod logs show: 
`[HPM] Error occurred while trying to proxy request /api/v1/namespaces/<namespace_name>/jobs/assortmentmasteraccumulateddaily/runs?limit=100&offset=0 from <MARQUEZ_WEB_DNS_URL> to http:/MARQUEZ_API_CONTAINER_IP:5000/ (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

and the API pod is throwing 502 exceptions 

Context: https://marquezproject.slack.com/archives/C01E8MQGJP7/p1641384504097900

**Comment by Vaisakh-RB** [comment]
@TohnJhomas Any solution, Please let me know.
