### ISSUE TITLE
Migrate from java.sql.Timestamp / java.util.Date to java.util.Instant

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#183]
java.util.Date is apparently [no bueno](https://codeblog.jonskeet.uk/2017/04/23/all-about-java-util-date/).

**Comment by sshah-wework** [comment]
We seem to use a few different date formats. In some cases it's a long representing the UNIX timestamp, in other cases it's a Timestamp instance. All should be switched over to Instant.

**Comment by wslulciuc** [comment]
Fixed #484
