### ISSUE TITLE
Marquez Datasource facets are not displayed in Marquez UI

### ISSUE THREAD

**Issue by dvirgiln** [MarquezProject/marquez#1834]
Hello, 

I submitted a Datasource to Marquez. This is the datasource details when I query them using the Rest API:

```
{
  id: {
    namespace: "s3://hbi-dns-staging",
    name: "PCHG"
  },
  type: "DB_TABLE",
  name: "PCHG",
  physicalName: "PCHG",
  createdAt: "2022-01-11T16:15:54.887Z",
  updatedAt: "2022-01-11T16:56:04.093153Z",
  namespace: "s3://hbi-dns-staging",
  sourceName: "s3://hbi-dns-staging",
  fields: [],
  tags: [],
  lastModifiedAt: null,
  description: null,
  currentVersion: "c565864d-1a66-4cff-a5d9-2e43175cbf88",
  facets: {
    dataSource: {
      uri: "s3://hbi-dns-staging/sql-runner/2022-01-11/PCHG.avro",
      name: "s3://hbi-dns-staging",
      _producer: "ip-.dir.prod.aws.hollandandbarrett.comeu-west-1.com/",
      _schemaURL: "https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet"
    }
  }
}
```

There is a facet defined, but we are not able to see that reflected in the UI:
<img width="1092" alt="Screenshot 2022-01-11 at 17 22 13" src="https://user-images.githubusercontent.com/6932080/149126536-f34fd9bb-d8d3-451f-a800-a4d26dd35655.png">

**Comment by dvirgiln** [comment]
Hello @collado-mike ,

I want to have display the URI of the table. Where it is located. In this case the files are located in S3.

About the schema, it is interesting to have the schema, the different columns of the tables. I will incorporate the schema facet, but that is a different question.

This is the code we are using to publish the URI facet:

```
 openLineage
      .newDatasourceDatasetFacetBuilder()
      .name(name).uri(url)
```

**Comment by dvirgiln** [comment]
Hello @collado-mike 

Any idea?

**Comment by dvirgiln** [comment]
So no information about this dataset facet appears when there is no schema, but if I include a schema in the dataset, then all the facets details appear.

**Comment by collado-mike** [comment]
Hey, sorry about the delay - can you give me a repro case? i.e., the curl (or whatever) command you used to insert the dataset and read it from the API?

**Comment by wslulciuc** [comment]
@dvirgiln: We currently don't display the datasource details in the dataset view, but I think I'd be a great idea! I've added this issue to our [roadmap](https://github.com/orgs/MarquezProject/projects/1/views/4) 👍

**Comment by phixMe** [comment]
This is now available! 🥳 
<img width="794" alt="image" src="https://github.com/user-attachments/assets/40ac78b1-7630-455a-9170-b4d2528d4d75">
