### ISSUE TITLE
Expand Namespace character support

### ISSUE THREAD

**Issue by TohnJhomas** [MarquezProject/marquez#1839]
A spark integration is automatically creating the namespace `abfss://root@datalakedev.dfs.core.windows.net` for a user, despite the `@` symbol not being supported in namespaces. 

As a result, the api is sending 400 errors in response to runEvents. 

We should look into expanding to support a broader character set in order to head off these issues in the future. In the immediate sense, we at least need to support the @ symbol to get this user unstuck. 

This user has created an alias in the interim, but aren't able to fully resolve the problem without editing the spark integration

**Comment by darezik** [comment]
This also appears to be the root cause for #1793

**Comment by gage-russell** [comment]
@wslulciuc Why was this closed?

https://github.com/MarquezProject/marquez/pull/1925 addresses maximum length of 1024 characters.

But the issue is that @ is not included in the regex check for namespace.
