### ISSUE TITLE
Suggestion: Marquez UI focus on job and display just direct dependencies

### ISSUE THREAD

**Issue by dvirgiln** [MarquezProject/marquez#1859]
In marquez when your graph is super big it is really difficult to find the job that you are looking. 

Suggestions:
1. Focus the graph to the job you are looking when you load the page first.
2. Having the possibility of seeing all the graph or just the direct inputs/outputs for the job you are looking. Sometimes when you look in an specific job you do not want to see all the full graph with the connections to further jobs and previous jobs.

**Comment by dvirgiln** [comment]
I created a different ticket, that can be closed, but it is linked to this one. I amend a screenshot so you can understand the nature of the problem.

https://github.com/MarquezProject/marquez/issues/2014

**Comment by wslulciuc** [comment]
Thanks @dvirgiln! I'll close this issue and continue our discussion in #2014
