### ISSUE TITLE
Define `OpenLineageResource(OpenLineageService)` constructor

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1868]
When constructing a new `OpenLineageResource` object, a `ServiceFactory` is required therefore not allowing users to inject, possibly their own, `OpenLineageService` implementation. Let's define the constructor `OpenLineageResource(OpenLineageService)` and deprecate the usage of `OpenLineageResource(ServiceFactory)`.

**Comment by fm100** [comment]
Every resources inherits `BaseResource` with a constructor getting `ServiceFactory`, and we may want to do some overall refactoring to create resourses only with the actual dependencies to be injected.
