### ISSUE TITLE
DB Migration Failure

### ISSUE THREAD

**Issue by isamatha** [MarquezProject/marquez#1871]
Hi,
I am trying to install marquez on a kubernetes cluster using helm install. I have postgres instance configured and updated the credentials accordingly in values.yaml file. The marquez pod does not come up and the log shows it failed db migration.

! Causing: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException:
! Migration V29__alter_dataset_versions_add_fields.sql failed
! -----------------------------------------------------------
! SQL State  : 42601
! Error Code : 0
! Message    : ERROR: syntax error at or near "include"
!   Position: 79
! Location   : marquez/db/migration/V29__alter_dataset_versions_add_fields.sql (/usr/src/app/file:/usr/src/app/marquez-api-0.20.0.jar!/marquez/db/migration/V29__alter_dataset_versions_add_fields.sql)
! Line       : 37
! Statement  : create index runs_created_at_completed_index
!     on runs(created_at DESC)
!     include (job_name, namespace_name, started_at, ended_at)
!     where current_run_state = 'COMPLETED'

Tried again by setting migrateOnStartup to false and that fails with error:
ERROR [2022-02-09 18:51:56,550] marquez.db.DbMigration: Failed to apply migration! You must apply the migration manually using the flyway command 'flyway migrate', or set 'MIGRATE_ON_STARTUP=true' to automatically apply migrations to your database.
How do I get past these errors and get marquez running?

**Comment by fm100** [comment]
Which version of postgresql are you using?

**Comment by isamatha** [comment]
Its postgres 10.1

**Comment by fm100** [comment]
Migration V29 contains `INCLUDE` clause when creating index, which is supported since postgresql 11. We recommend to use postgres 12.1 or higher: https://github.com/MarquezProject/marquez#requirements

**Comment by isamatha** [comment]
I updated to postgres 12.1 and it's working now. Thanks.
