### ISSUE TITLE
API versioning / evolution?

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#19]
What are everyone's thoughts regarding how to version the API? Versioning (via URI or headers) or [evolution](https://philsturgeon.uk/api/2018/05/02/api-evolution-for-rest-http-apis/)? Or something else?

**Comment by wslulciuc** [comment]
+1 for URI-based versioning (e.g. `https://api.marquez.com/v1`). My preference would be to use a versioning scheme that is common and well known. Makes testing and evolving the API more predictable.

[API Versioning Has No “Right Way”](https://blog.apisyouwonthate.com/api-versioning-has-no-right-way-f3c75457c0b7) is a great blog outlining possible alternatives.

@hougs @julienledem : Any preference?

**Comment by sshah-wework** [comment]
:thumbs up: URI-based feels like the most conventional approach. Have worked with an evolution approach and deprecation felt a bit more difficult as the API got more consumers.

**Comment by wslulciuc** [comment]
We'll prefix all API endpoints with `/api/v1` #104
