### ISSUE TITLE
FATAL: database "marquez" does not exist error

### ISSUE THREAD

**Issue by isamatha** [MarquezProject/marquez#1903]
I am trying to install marquez using helm chart, using an existing postgres database (version 12.20). The marquez pod is failing with this error.

INFO  [2022-03-08 19:05:28,731] marquez.MarquezApp: Running startup actions...
INFO  [2022-03-08 19:05:28,751] org.flywaydb.core.internal.license.VersionPrinter: Flyway Community Edition 6.5.7 by Redgate
ERROR [2022-03-08 19:05:29,529] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
! org.postgresql.util.PSQLException: FATAL: database "marquez" does not exist
! at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
! at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2787)
! at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:173)
! at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:290)
! at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
! at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
! at org.postgresql.Driver.makeConnection(Driver.java:400)
! at org.postgresql.Driver.connect(Driver.java:259)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:347)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:228)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:769)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:697)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:496)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:121)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:110)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:134)
! at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
! at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:80)
! at org.flywaydb.core.Flyway.execute(Flyway.java:453)
! at org.flywaydb.core.Flyway.info(Flyway.java:331)
! at marquez.db.DbMigration.hasPendingDbMigrations(DbMigration.java:68)
! at marquez.db.DbMigration.migrateDbOrError(DbMigration.java:23)
! at marquez.MarquezApp.run(MarquezApp.java:96)
! at marquez.MarquezApp.run(MarquezApp.java:40)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at marquez.MarquezApp.main(MarquezApp.java:52)
INFO  [2022-03-08 19:05:29,532] marquez.MarquezApp: Stopping app...

**Comment by wslulciuc** [comment]
Hey, @isamatha! Did you create the `marquez` database in your existing postgres instance? As a reference, you can checkout [`init-db.sh`](https://github.com/MarquezProject/marquez/blob/main/docker/init-db.sh)  used for running Marquez locally via docker, or the [Configuration](https://github.com/MarquezProject/marquez#configuration) section in our `README.md`

**Comment by isamatha** [comment]
That seems to be the issue. Once I manually created the db, I was able to get marquez running. The configuration mentioned about seems to be geared towards docker environment. I am running marquez on kubernetes. Is there any documentation to configure and run HTTP API server on kubernetes?

**Comment by wslulciuc** [comment]
We do! You can check out our [deployment overview](https://marquezproject.github.io/marquez/deployment-overview.html) docs outlining how to run Marquez on Kubernetes.

**Comment by wslulciuc** [comment]
@isamatha, let us know if we can close this issue!

**Comment by isamatha** [comment]
Yes, this can be closed.
