### ISSUE TITLE
UI does not escape dataset name in GET request

### ISSUE THREAD

**Issue by cerveada** [MarquezProject/marquez#1904]
I got:

Something went wrong while fetching dataset runs

Seems like this request:
```
http://localhost:3000/api/v1/namespaces/default/datasets/file:/Users/foo/projects/spline-spark-agent/examples/data/output/batch/job1_results/versions?limit=100&offset=0
```

should be escaped like this:
```
localhost:3000/api/v1/namespaces/default/datasets/file%3A%2FUsers%2Ffoo%2Fprojects%2Fspline-spark-agent%2Fexamples%2Fdata%2Foutput%2Fbatch%2Fjob1_results/versions?limit=100&offset=0
```

This happens in job graph when I click on dataset node.

**Comment by wslulciuc** [comment]
@phixMe, looks like we may have missed escaping some calls in the UI?

**Comment by phixMe** [comment]
Hey @cerveada,

I made this PR a few months ago, but didn't find anybody in the community around to test the changes I made.

Can you possibly try this out? https://github.com/MarquezProject/marquez/pull/1668

**Comment by cerveada** [comment]
>  Can you possibly try this out? https://github.com/MarquezProject/marquez/pull/1668

I tried to run from that branch using `./docker/up --build` and the bug is still there.

The PR seems to be doing changes in **lineage** endpoint, but this bug is in **namespaces** endpoint.

**Comment by phixMe** [comment]
@cerveada I looked a little deeper on this one and created a dataset with the name you provided in our test environment. It looks like we are escaping the url correctly from what I can tell. (See screenshot below)

Our request code seems to be ok as well fetching dataset versions as well.
https://github.com/MarquezProject/marquez/blob/main/web/src/store/requests/datasets.ts#L16-L28

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/7514204/157736597-07906ad1-3b01-4b4e-b855-fe529cc3e773.png">

Do you have an easy way to recreate this one?

**Comment by cerveada** [comment]
I was running Marquez using `./docker/up.sh` in that version (I don't know which one is it by default) the bug is present.

Using `./docker/up.sh --build` in the current main branch the bug is fixed.

So it seems to be fixed in the main branch and this ticket can be probably closed.
