### ISSUE TITLE
Update OpenLineage implementation to support metadata outside of runs

### ISSUE THREAD

**Issue by collado-mike** [MarquezProject/marquez#1930]
OpenLineage is going to support adding dataset and (possibly) job metadata outside of the context of a run (e.g., team ownership of a dataset, etc.). Marquez will need to be updated to support the new event type when it's been spec'ed - https://github.com/OpenLineage/OpenLineage/issues/323

**Comment by wslulciuc** [comment]
Supported added in:
* https://github.com/MarquezProject/marquez/pull/2641
* https://github.com/MarquezProject/marquez/pull/2661
