### ISSUE TITLE
Write backfill script for Airflow parent runs

### ISSUE THREAD

**Issue by collado-mike** [MarquezProject/marquez#1944]
As described in https://github.com/OpenLineage/OpenLineage/pull/664 , the OpenLineage Airflow implementation has always sent back the `ParentRunFacet` with less than correct information in the `runId` and job `name` fields. It's possible to backfill this information in existing databases, which is necessary for a complete and correct implementation of https://github.com/MarquezProject/marquez/issues/1928 .

The approach would be to split the parent job name on the `.` character to determine the DAG name and concatenate that with the runId (usually something like `scheduled__2022-03-14T01:40:10+00:00`) to generate UUID (see UUIDv3 generation in the OpenLineage implementation [here](https://github.com/OpenLineage/OpenLineage/pull/664/files#diff-8e72bf6ecb963d51e58a9634263944ea68351d9f62c896653624d94cb13dd15aR156)). *Note* that some job names have the DAG followed by the task group, _then_ the task id, all separated by `.` characters, so we should choose the left-most name of the task id.

**Comment by conorbev** [comment]
Done
