### ISSUE TITLE
Support Job renaming and symlinking

### ISSUE THREAD

**Issue by collado-mike** [MarquezProject/marquez#1946]
In the design for https://github.com/MarquezProject/marquez/issues/1928 , it is proposed that extra logic be added to Marquez to redirect job URLs that use the job's original simple name to instead point to the job's Fully Qualified Name (FQN). In the current design, a view is used to return the FQN of an existing job as the `name` field of `Job` records, minimizing the SQL changes needed to construct/return the FQN while avoiding the high cost of backfilling the `jobs`, `runs`, `lineage_events`, and `job_version` tables, all of which refer to a job by name.

As an alternative to using a view, we also have a need to support job renaming/symlinking. This is useful for a host of other reasons, including

* changing the namespace of a job because team ownership has changed
* adding a task group to an existing Airflow DAG, which changes the FQN of a job
* physical plan changes in Spark, which could change the generated job name

By supporting Job symlinks, a simpler backfill script for #1928 could insert new jobs with the fully qualified name defined and update the existing job to symlink to the new one. Old `runs` and `lineage_events` records can continue to point to the existing `jobs` record without a backfill and logic in Marquez would be responsible for merging the jobs. 

It's worth noting that _every_ API in Marquez that refers to a job would need to implement the logic to find and process all symlinks for a queried Job and merge all results. For example, the `/lineage` API would need to determine all of the jobs linked to every job present in the graph and to then merge all subsequent graphs into a single graph with symlinked jobs deduped. The `/runs` API would need to find the latest runs for any job symlinked to the requested one and the runs would need to be merged so that they are in time order regardless of which job name a given run points to.

Symlinks could be recursive and can be many-to-one, so that navigating symlinks would be modeled as a tree-traversal of arbitrary depth (practically probably one or two). ~~This would be modeled in the Marquez API code, as modifying all existing SQL to capture everything is likely impossible.~~ (untrue - see below comment)

**Comment by collado-mike** [comment]
Practically, we can probably make the simplifying assumption that a job symlink path is linear rather than a tree. If we make the job symlink relationship 1:1 rather than many-to-one, we can modify the existing lineage query to something like the following:

```sql
          WITH RECURSIVE
              job_symlink AS (
                SELECT uuid, current_version_uuid, symlink_target
                FROM jobs j
                UNION
                SELECT j.uuid,
                COALESCE(j.current_version_uuid, js.current_version_uuid) AS current_version_uuid,
                j.symlink_target
                FROM jobs j
                INNER JOIN jobs_sylink js ON j.uuid=js.symlink_target
              )
              job_io AS (
                  SELECT j.uuid AS job_uuid,
                  ARRAY_AGG(DISTINCT io.dataset_uuid) FILTER (WHERE io_type='INPUT') AS inputs,
                  ARRAY_AGG(DISTINCT io.dataset_uuid) FILTER (WHERE io_type='OUTPUT') AS outputs
                  FROM job_symlink j
                  LEFT JOIN job_versions v on j.current_version_uuid = v.uuid
                  LEFT JOIN job_versions_io_mapping io on v.uuid = io.job_version_uuid
                  WHERE j.symlink_target IS NULL
                  GROUP BY j.uuid
              ),
              lineage(job_uuid, inputs, outputs) AS (
                  SELECT job_uuid, inputs, outputs, 0 AS depth
                  FROM job_io
                  WHERE job_uuid IN (<jobIds>)
                  UNION
                  SELECT io.job_uuid, io.inputs, io.outputs, l.depth + 1
                  FROM job_io io,
                       lineage l
                  WHERE io.job_uuid != l.job_uuid AND
                  array_cat(io.inputs, io.outputs) && array_cat(l.inputs, l.outputs)
                  AND depth < :depth"
              )
          SELECT DISTINCT ON (l2.job_uuid) j.*, inputs AS input_uuids, outputs AS output_uuids, jc.context
          FROM lineage l2
          INNER JOIN jobs j ON j.uuid=l2.job_uuid
          LEFT JOIN job_contexts jc on jc.uuid = j.current_job_context_uuid
```
Since we only ever build lineage on the current version of a job, we simply need to determine the current job version in order to compute its inputs and outputs. If job symlinks are 1:1, we just need to get the current version of the latest job in the chain that has a `current_version_uuid` value.

Pretty much everything else in the JobsResource can be handled by a filter that redirects symlinked jobs to the latest job in the symlink chain. The only exception is the `/runs` API, which returns the latest runs for a job. That can be handled in SQL with the following change to the existing query
```sql
          WITH RECURSIVE job_names AS (
            SELECT uuid, name, namespace_name, symlink_target
            FROM jobs
            WHERE name=:jobName AND namespace_name=:namespace
            UNION
            SELECT j.uuid, j.name, j.namespace_name, j.symlink_target
            FROM jobs j
            INNER JOIN job_names jn ON jn.symlink_target=j.uuid OR jn.uuid=j.symlink_target
          )
          SELECT r.*, ra.args, ctx.context, f.facets,
          jv.version AS job_version,
          ri.input_versions, ro.output_versions
          FROM (
            SELECT * FROM runs r
            INNER JOIN job_names jn ON jn.namespace_name=r.namespace_name AND jn.name=r.job_name
          ) r
          LEFT OUTER JOIN
          (
            SELECT le.run_uuid, JSON_AGG(event->'run'->'facets') AS facets
            FROM lineage_events le
            INNER JOIN runs r2 ON r2.uuid=le.run_uuid
            WHERE r2.job_name=:jobName AND r2.namespace_name=:namespace
            GROUP BY le.run_uuid
          ) AS f ON r.uuid=f.run_uuid
          LEFT OUTER JOIN run_args AS ra ON ra.uuid = r.run_args_uuid
          LEFT OUTER JOIN job_contexts AS ctx ON r.job_context_uuid = ctx.uuid
          LEFT OUTER JOIN job_versions jv ON jv.uuid=r.job_version_uuid
          LEFT OUTER JOIN (
           SELECT im.run_uuid, JSON_AGG(json_build_object('namespace', dv.namespace_name,
                  'name', dv.dataset_name,
                  'version', dv.version)) AS input_versions
           FROM runs_input_mapping im
           INNER JOIN dataset_versions dv on im.dataset_version_uuid = dv.uuid
           GROUP BY im.run_uuid
          ) ri ON ri.run_uuid=r.uuid
          LEFT OUTER JOIN (
            SELECT run_uuid, JSON_AGG(json_build_object('namespace', namespace_name,
                                                        'name', dataset_name,
                                                        'version', version)) AS output_versions
            FROM dataset_versions
            GROUP BY run_uuid
          ) ro ON ro.run_uuid=r.uuid
          ORDER BY STARTED_AT DESC NULLS LAST
          LIMIT :limit OFFSET :offset
```
Here, the WHERE clause is moved into a recursive CTE and the runs table is joined based on job names - the runs for any job that is symlinked to the queried job will be in the results, sorted by latest first.

**Comment by collado-mike** [comment]
Given the above, I think we can implement symlinks with the following:
1. Add a migration script
```sql
ALTER TABLE jobs ADD COLUMN symlink_target uuid REFERENCES jobs (uuid);
```
2. Add a filter on the `/jobs/*` APIs to redirect jobs that have a symlink to the latest job in the symlink chain (no more than one redirect).
3. Update the `/lineage` API SQL with the above changes
4. Update the `/runs` API SQL with the above changes
5. Update the `OpenLineageDao` to always link a `Run` with the latest job in the symlink chain - even if the run event points to the old job name **This prevents us from updating the `current_version_uuid` of an old job.**

**Comment by conorbev** [comment]
Done
