### ISSUE TITLE
Job Run Duration Shows incorrect time if >1 hour or >24 hours

### ISSUE THREAD

**Issue by mlecuyer-nd** [MarquezProject/marquez#1949]
**Description of Problem**
When having a run with a duration longer than 23 hours, the hours do not increment past 24, and instead roll back over to 0.
Additionally, when a job is >1h, it shows `hours` and `seconds` but not minutes, leading to confusing metrics.

**Expected Behavior**
Duration will show `start_time - end_time` in hours, minutes, and seconds

**Observed Behavior**
Duration shows only hours and seconds, and rolls over to 0 after 23 hours.

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/77695021/163627129-7f120007-7477-4a2b-94b8-ae7e3b9f6301.png">

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/77695021/163627175-18ff00ac-05fd-4805-89ca-56d1f3ca5d95.png">

**Steps to reproduce**
* Set up quick start container
* POST tutorial job start
* Edit tutorial job `completed` time to be >1h later
* POST job `complete`
* view job duration in UI

**Comment by phixMe** [comment]
Thanks for reporting this issue. I've got a fix ready.
