### ISSUE TITLE
Add back static code analysis plugin

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1976]
PR https://github.com/MarquezProject/marquez/pull/1055 removed the `spotbugs` plugin. The plugin was removed as the CI build failed when bugs in the codebase were found. The [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en) badge requires that we have some static code analysis tool in place, so this issue is to ensure the plugin is added back.

Note, when adding the `spotbugs` plugin, the PR should also address all errors and warnings to avoid polluting the logs and breaking CI.

**Comment by merobi-hub** [comment]
Took the liberty of editing the title to reflect the new tool.
