### ISSUE TITLE
investigate NamespaceDAOTest::testFindAll is flakiness on CircleCI

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#198]
Always fails the first time, passes the second time on CircleCI. This does not happen locally.

**Comment by ashulmanWeWork** [comment]
Sample run where this happens: https://circleci.com/gh/MarquezProject/marquez/1173?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by sshah-wework** [comment]
Haven't run into this again -- closing out for now.
