### ISSUE TITLE
display closest nodes not all the nodes in the tree

### ISSUE THREAD

**Issue by dvirgiln** [MarquezProject/marquez#2014]
When the datasets in the namespace are growing it is impossible to use marquez ui to follow dependencies. 

I ve attached an image of a subset of the graph
<img width="1578" alt="Screenshot 2022-06-08 at 08 26 48" src="https://user-images.githubusercontent.com/6932080/172557808-c7bcb733-1261-4ce9-a1ea-01e57e9b959a.png">

You can see that is impossible to follow.  This is in my company what everyone is complaining. If they want to see the lineage of one dataset, they see all the tree with things that they are not really interested. Ideally I would display a button or filter where you can decide how many levels you want to see, and by default you just see one level downstream nodes and one level upstream nodes. 

Hope it is clear

**Comment by wslulciuc** [comment]
@dvirgiln: You're absolutely right, for very large graphs it's hard to navigate / follow dependencies (not a great experience). Usability is something we've been meaning to address, and there's plenty of room for improvement here. I can start opening issues that outline some of the changes we'd like to make in the UI (with mockups), but I also encourage you to do the same and open UI issues and labeliing them with [`web`](https://github.com/MarquezProject/marquez/labels/web) and [`feature`](https://github.com/MarquezProject/marquez/labels/feature). I'll make sure to add the issues to our [roadmap](https://github.com/orgs/MarquezProject/projects/1/views/4?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C2807312%2C%22Labels%22%5D)

To give you a sneak peek of what changes we'd like to make the lineage graph navigation, you can checkout [`demo.datakin.com`](https://demo.datakin.com/lineage/job/food_delivery/etl_orders.etl_categories)(Datakin is powered by Marquez ❤️ ):

<img width="1005" alt="Screen Shot 2022-06-10 at 4 51 52 PM" src="https://user-images.githubusercontent.com/1553185/173163631-9a5e5cf1-0ac5-487f-b1b4-f53740e41275.png">

The UI above uses the Marquez LineageAPI, but applies client-side grouping logic. The team is currently discussing the effort to begin moving the dataset and job grouping logic to Marquez. What are your initial thoughts? _Also, I think deciding on how many levels deep in the graph should be rendered is already supported by the LineageAPI, it's just a matter of providing that option to the user 😄
