### ISSUE TITLE
I can't see old version id lineage for dataset and job in marquez ui

### ISSUE THREAD

**Issue by rahulgoyal2987** [MarquezProject/marquez#2016]
I can't see old version id lineage for dataset and job in marquez ui. Even can't see which old job id is linked to which dataset id

**Comment by wslulciuc** [comment]
@rahulgoyal2987: When you click on the `VERSION HISTORY` or `RUN HISTORY` tabs, you don't see a list of versions or runs? Mind providing a screenshot? Also, what version of Marquez are you running?

**Comment by wslulciuc** [comment]
@rahulgoyal2987: Are you still seeing this issue? Let us know, we'd love to help or maybe file a bug if needed.

**Comment by wslulciuc** [comment]
@rahulgoyal2987, closing... but let's us know if you are still seeing this issue and we'd be happy to reopen this issue.
