### ISSUE TITLE
Latest version of marquez-web docker image is crashing after commit 6c69fa2

### ISSUE THREAD

**Issue by YLibert** [MarquezProject/marquez#2061]
Hi, 

### Setup
I'm using the Helm chart to deploy marquez in a EKS cluster

### Problem
After the commit [6c69fa2](https://github.com/MarquezProject/marquez/commit/6c69fa2760c77b11180c6cea216da3bc1da93050)
The deployment of the latest marquez-web image is producing an error:

`standard_init_linux.go:228: exec user process caused: no such file or directory`

**Comment by wslulciuc** [comment]
@YLibert: This issue has been fixed in the `0.25.0` release by PR https://github.com/MarquezProject/marquez/pull/2059. Let us know if that's not the case!
