### ISSUE TITLE
Regular release schedule/policy are needed

### ISSUE THREAD

**Issue by merobi-hub** [MarquezProject/marquez#2072]
The project currently lacks a consistent, reliable cadence for releases. A clear policy approved by the community would help us establish a regular schedule for releases. Out-of-phase releases could still be possible (and we already have a policy in place for these).

Proposed: present policy language to the community establishing a monthly cadence for releases. Upon approval, open a PR to add the policy to the docs.

**Comment by wslulciuc** [comment]
Great idea, @merobi-hub 💯 🥇
