### ISSUE TITLE
[PROPOSAL] Add Boring Cyborg Github app to project 

### ISSUE THREAD

**Issue by merobi-hub** [MarquezProject/marquez#2080]
[Boring Cyborg](https://github.com/kaxil/boring-cyborg) by [@kaxil](https://github.com/kaxil) is a Github app that automates "boring" Github tasks such as PR labeling and new contributor greeting. It also, naturally, makes such actions happen more consistently and reliably across a project. [Airflow](https://github.com/apache/airflow/blob/main/.github/boring-cyborg.yml) uses the app to label PRs, greet new contributors upon first PRs and issues, congratulate users on merged PRs, and check if branches are up to date prior to merging. We could use it for some or all of these actions.

To add it to the project, we would need to [install the Github app](https://github.com/apps/boring-cyborg), assign it to the repository, and add a `boring-cyborg.yml` file to the project's `.github` directory.

To get a sense of the configuration options and functionality, you can see a configuration file for OpenLineage here: https://github.com/merobi-hub/OpenLineage/blob/main/.github/boring-cyborg.yml

And here's Airflow's `boring-cyborg.yml`: https://github.com/apache/airflow/blob/main/.github/boring-cyborg.yml

**Comment by wslulciuc** [comment]
@merobi-hub: I think this is a great idea 💯. Did you want to open a PR to add configuration to greet contributors?
