### ISSUE TITLE
Unable to spin up Marquez following instructions found in README

### ISSUE THREAD

**Issue by mzareba382** [MarquezProject/marquez#2088]
There is probably a lack of documentation regarding on how to satisfy all the requirements to 'Quickstart' local Marquez environment using `docker/up.sh`- specifically for setting up MARQUEZ_CONFIG env variable/editing a config file.

Up-to-date on main (development) branch.

Neither of the following would work for me:
`./docker/up.sh`
`./docker/up.sh --build`
`./docker/up.sh --api-port 9000`

marquez-api gives following error and code 1:
```
marquez-api | wait-for-it.sh: db:5432 is available after 1 seconds
marquez-api | WARNING 'MARQUEZ_CONFIG' not set, using development configuration.
marquez-api | invalid choice: 'marquez-api-0.26.0-SNAPSHOT.jar' (choose from 'server', 'check', 'seed')
marquez-api | usage: java -jar marquez-api-0.25.0-SNAPSHOT.jar
marquez-api |        [-h] [-v] {server,check,seed} ...
marquez-api | 
marquez-api | positional arguments:
marquez-api |   {server,check,seed}    available commands
marquez-api | 
marquez-api | named arguments:
marquez-api |   -h, --help             show this help message and exit
marquez-api |   -v, --version          show the application version and exit
marquez-api exited with code 1
```

marquez-db and marquez-web scripts are being executed correctly.

Machine is 2019 Intel MacOS Monterey 12.5.1
Docker versions are:
```
Engine: 20.10.17
Compose: 1.29.2
```

**Comment by mzareba382** [comment]
Executing `./gradlew clean build` before `./docker/up.sh` helped.

**Comment by wslulciuc** [comment]
Great to hear the issue has been resolved, @mzareba382!
