### ISSUE TITLE
Point in time lineage proposal

### ISSUE THREAD

**Issue by pawel-big-lebowski** [MarquezProject/marquez#2117]
Extend column lineage endpoint to be able to show how the graph looked like for a specified timestamp or dataset version. 

See proposal for more details:
https://github.com/MarquezProject/marquez/blob/main/proposals/2045-column-lineage-endpoint.md

**Comment by howardyoo** [comment]
Do we currently have this similar feature for dataset also? Just checking...

**Comment by pawel-big-lebowski** [comment]
@howardyoo I think we don't but we wanted to add one. Perhaps this deserves another `lineage over time` epic.
