### ISSUE TITLE
Marquez /namespace/{ns}/dataset/{d} endpoint duplicating fields that have changed

### ISSUE THREAD

**Issue by conorbev** [MarquezProject/marquez#2160]
For example if a dataset has a column `discount_id` that in one version is a `INTEGER` type and it changes to `VARCHAR` in another version then when you retrieve the dataset via API both "versions" of that column will be returned.

**Comment by tnazarew** [comment]
@conorbev I tried to replicate the issue but everything works fine for me. Could you give more details?

**Comment by mobuchowski** [comment]
I was also unable to reproduce it.

**Comment by conorbev** [comment]
@wslulciuc This shows up in the datakin seed data? Is it possible that the seed data itself has the bug?

**Comment by harels** [comment]
Can't reproduce this issue anymore
