### ISSUE TITLE
Vulnerability assessment tool scans

### ISSUE THREAD

**Issue by lulciuca** [MarquezProject/marquez#22]
I recommend that we introduce vulnerability scans early in this project so that we can keep our security posture healthy. We can achieve this by performing security scans (with a tool) on PR's and rejecting them if they introduce new vulnerabilities. At a minimum, we should be scanning our dependencies since it's rather easy to do and incurs little overhead. [Snyk](https://snyk.io/docs/github) is a solid choice for this purpose.

In the future, we'll want to scan custom code as well (the code we actually wrote), but those types of scans are usually more cumbersome to perform and orchestrate. I don't think this needs to be tackled right away, however, it should be considered carefully.

**Comment by wslulciuc** [comment]
+1

Great idea to introduce this early. @ashulmanWeWork, thoughts? and what have you used in the past for vulnerability scans?
