### ISSUE TITLE
General Ui suggestions Highlight upstream/downstream datasets/jobs

### ISSUE THREAD

**Issue by davidsharp7** [MarquezProject/marquez#2218]
It would be really useful to be able once a dataset/job is clicked on if the all the upstream and down stream jobs and datasets were highlighted for ease of identification.

Secondly if a dataset/job is selected the UI should take you directly to the dataset as opposed to having to search for it.

having a simpler zoom in or zoom out capability would also be helpful.

Also being able to control the depth of the lineage from Ui would be useful.

**Comment by ShreyasGit51283** [comment]
Worked on designs for the visiblity and selection of lineage .
https://github.com/MarquezProject/marquez/issues/2428 
@davidsharp7 please do review.

**Comment by davidsharp7** [comment]
Yes that highlighting was exactly what I thinking of. The other thing that might useful is the ability to group objects so that larger data projects can find components easily.

**Comment by harels** [comment]
closing this issue, and we'll track remaining work here #2378
