### ISSUE TITLE
Point in time column lineage endpoint - implementation

### ISSUE THREAD

**Issue by pawel-big-lebowski** [MarquezProject/marquez#2262]
Implement point in time column-level lineage endpoint according to the proposal in #2117 2193

**Comment by wslulciuc** [comment]
Related issues https://github.com/MarquezProject/marquez/issues/1519

**Comment by pawel-big-lebowski** [comment]
todo list

 * implement point-in-time endpoint -> PR #2265
 * support point-in-time together with `withDownstream` feature,
 * implement Java client -> #2269
 * implement Python client.
