### ISSUE TITLE
Define class RunId

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#229]
Let's define the **class** `RunId` that both encapsulates and validates a given job run ID. This will simplify how we handle job run state transitions. That is, instead of the `JobService` taking a UUID as a parameter on state transitions, we can pass a known type! The class should be added to the `marquez.common.models` pkg.

This will also allow us to bind the `id` path param to a `RunId`! 
```java
@PUT
@Path("/jobs/runs/{id}/abort")
public Response abortRun(@PathParam("id") RunId runId) {
 jobService.abortRun(runId);
 ...
}
```

We can then update the **JobService** interface with the following methods (addressed in a separate issue #230):

```java
JobService.updateRunState(RunID, RunState)
``` 

Use [Namespace](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/common/models/Namespace.java) as an example.

**Comment by wslulciuc** [comment]
@sshah-wework : Think we can simplify updating the job run state with `JobService.setRunState(JobRunID, RunState)`

**Comment by ashulmanWeWork** [comment]
I like this idea - the benefit is that we're always carrying around a valid ID. It makes a certain set of errors impossible.

My only concern is that for validation, what level should we tune the error handling to? I'm thinking it should throw a resource-related exception that the exception mapper will catch. However, then we're passing that logic around the service layer and other parts, where it makes less sense. Maybe at those places, we can just pass a raw string or UUID?

**Comment by lulciuca** [comment]
I've had a similar realization myself with respect to defining fine grained data-points as their own types. Nice to see we're thinking a like!

**Comment by sshah-wework** [comment]
@wslulciuc re: a `JobRunID` type, it makes sense and follows what you introduced with a `Namespace` type as well. 👍 

Re #230: It doesn't seem necessary to have a separate service method for each possible job run state. its more to test and maintain.

**Comment by wslulciuc** [comment]
>  It doesn't seem necessary to have a separate service method for each possible job run state. its more to test and maintain.

Yeah, seems a bit heavy. Updated issue #230 to reflect our discussion here.
