### ISSUE TITLE
Update JobService interface

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#230]
Let's keep a consist interface across services: For example, `create()` to create a new instance of some object A. The `JobService` defines method names with the pattern `*Job`, but we can clean things up a bit given that the service performs actions on a job instance.

### [`JobService`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/core/services/JobService.java)

* `create()` - Create a Job
* `get()` - Retrieve a job
* `getLatestVersion()` - Retrieve the latest version of a job
* `getAllVersions()` - Retrieve all versions of a job
* `getAll()` - Retrieve all jobs
* `updateRunState()` - Sets job run state to: `NEW`, `RUNNING `, `COMPLETED`, `FAILED`, or `ABORTED`

Ideally, we'll want to address issue #229 first that introduces class JobRunId

**Comment by wslulciuc** [comment]
Yep, we'll want to eventually update the contract to use the defined type discussed in issue #229. We can still define the method as `updateRunState()` without `Job` as we're invoking actions on a `JobService`, so seems a bit redundant

**Comment by wslulciuc** [comment]
Exactly, it's more for setting expectations That is,  if I'm using a service I know I can perform a certain set of actions.

**Comment by sshah-wework** [comment]
Gotcha, I think it works for CRUDy operations. For less CRUDy things, we can just continue to name descriptively?

**Comment by wslulciuc** [comment]
> For less CRUDy things, we can just continue to name descriptively?

Yep, sounds like a solid naming convention to me! For more service-specific logic / actions, more context on the methods _action_ is preferred.

**Comment by sshah-wework** [comment]
Cool, sounds great 😎

**Comment by wslulciuc** [comment]
Fixed #627
