### ISSUE TITLE
Events icon returning 404

### ISSUE THREAD

**Issue by merobi-hub** [MarquezProject/marquez#2316]
The events icon (`iconSearchArrow`) is no longer visible in the sidenav.

**Comment by mobuchowski** [comment]
I can see it: 

<img width="136" alt="Screenshot 2023-01-10 at 13 35 23" src="https://user-images.githubusercontent.com/6503007/211553343-ca144874-6341-470e-8326-dad8867d3903.png">

How did you run Marquez that it's not visible?

**Comment by merobi-hub** [comment]
This got fixed and then broken and then fixed again since I created this issue, I believe. Here's the latest fix: https://github.com/MarquezProject/marquez/pull/2321

**Comment by wslulciuc** [comment]
@merobi-hub, yeah having the icons not working isn't a great experience ☹️ but I'm pretty sure the latest build and release have the icons.
