### ISSUE TITLE
Populate namespace_ownership table on ownership changes

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#232]

**Comment by sshah-wework** [comment]
Removing this from `0.2.0`. This is a nice to have but there's a lot to do before 3/31 to make this milestone.

**Comment by sshah-wework** [comment]
LMK if you feel strongly about it.

**Comment by wslulciuc** [comment]
I agree. Let's punt on this feature until next release. Thanks for revisiting the priority of `0.2.0`

**Comment by wslulciuc** [comment]
Fixed #627
