### ISSUE TITLE
Allow users to set depth of lineage graph in UI

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#2378]
In the Marquez UI, the user is not provided with the option to set the depth of the lineage graph even though the [LineageAPI](https://marquezproject.github.io/marquez/openapi.html#operation/getLineage) defines a `depth` param. Therefore, the [lineage call](https://github.com/MarquezProject/marquez/blob/main/web/src/store/requests/lineage.ts#L10) defaults to `20` on the [backend](https://github.com/MarquezProject/marquez/blob/main/api/src/main/java/marquez/api/OpenLineageResource.java#L47). 

**Benefits**:

1. Reduce lineage graph render complexity i.e. a dynamic `depth` of `N` would return a more digestible lineage UI view for debugging
2. Reduce lineage graph call response time i.e.  a dynamic `depth` of `N` would avoid returning a lineage graph with all connected nodes from `origin` node

**Comment by davidsharp7** [comment]
Related to [2218](https://github.com/MarquezProject/marquez/issues/2218)
