### ISSUE TITLE
Publish design doc 

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#242]
Let's publish the [Marquez draft design](https://drive.google.com/open?id=1zxvp-6jv4Gs7eAGFmK0fbKbYL9cbEQrRJKLk3ez4PRA) to this repo to allow public access to the doc.

**Comment by villasv** [comment]
Still waiting for it :-P

But judging the recent activity on https://github.com/MarquezProject/marquez/pull/243, this is still happening, right?

**Comment by wslulciuc** [comment]
Hey, @villasv! Absolutely. The roadmap and documentation for Marquez is in the works (though taking longer than we'd like). Good news is that we'll be finalizing / cleaning up #243 this week, with the PR landing in `master` early next week, giving https://marquezproject.github.io/marquez some much needed attention!

**Comment by wslulciuc** [comment]
@villasv: We're still on track to make the Marquez roadmap and documentation public this week. There's a slight delay publishing the doc given Q1 ends for us this week and our current focus is to wrap up the changes + merge #395

**Comment by wslulciuc** [comment]
@villasv,  Marquez overview now ready for feedback #457 :)
