### ISSUE TITLE
Proposal for improving the visibility of lineage

### ISSUE THREAD

**Issue by ShreyasGit51283** [MarquezProject/marquez#2428]
The Problem
When opening a lineage from a table views, in crowded lineages
- It's difficult to identify the node selected whose lineage is highlighted
- The highlighted lineage also needs a stronger visual contrast to be able to trace it easily. 

Solution
- Figma click through proposal - https://www.figma.com/proto/VvabDMuRKIdb3sSczCjUVR/Marquez?node-id=112%3A1033&scaling=min-zoom&page-id=18%3A0&starting-point-node-id=112%3A1033&show-proto-sidebar=1
- Figma designs 
https://www.figma.com/file/VvabDMuRKIdb3sSczCjUVR/Marquez?node-id=112%3A420&t=kEH2PlubYlxWEt74-1

![Desktop - 5](https://user-images.githubusercontent.com/35736086/220002861-9dda8958-2c37-4bce-99db-a595d7260ce7.png)
![Desktop - 7](https://user-images.githubusercontent.com/35736086/220002866-c5d51095-39a5-4e55-b5ee-5dc0228d9349.png)

For this issues, would like help to make small incremental changes in the lineage graphs. The design maybe too radically different, so feedback and inputs please.
Thanks

**Comment by wslulciuc** [comment]
We're with you on this suggestion! Marquez now has clear higgling for the lineage path:

<img width="1031" alt="Screenshot 2024-10-23 at 3 49 06 PM" src="https://github.com/user-attachments/assets/3ea2d02b-5d5b-4f03-a58d-711a9a942c3e">
