### ISSUE TITLE
Proposal - Improving UX of the Table pages

### ISSUE THREAD

**Issue by ShreyasGit51283** [MarquezProject/marquez#2455]
https://www.figma.com/file/VvabDMuRKIdb3sSczCjUVR/Marquez?node-id=165%3A234&t=lBYOTsZo5hqUcxMg-1
<img width="730" alt="Screenshot 2023-03-20 at 4 23 10 PM" src="https://user-images.githubusercontent.com/35736086/226319776-9644b001-3f61-4a03-ac79-5b41a4ed0dde.png">

Proposal options for improving the table views.
The current state appears its not easy to quickly find results, and jump between result pages. 
Overall
- Added display row results number control
- Search on the table

Made  2 options - 
Option just incrementally improves the UX. Moved the result count and the pagination control close to each other so they are easy to consume.
Option2 - Introduces page numbers so users can easily find a result

I prefer option 2. 
Open to feedback

**Comment by wslulciuc** [comment]
@ShreyasGit51283 thanks for your input and design suggestions!
