### ISSUE TITLE
Connection error PostgreSQL and Marquez

### ISSUE THREAD

**Issue by TomEijk** [MarquezProject/marquez#2468]
Hi all! 

I really appreciate this repository and would love to use it for its data lineage aspect!
Last few days, I've been trying to get the `marquez api`  Docker image up and running but whatever I try, it does not seem to work. 

It returns the following errors in Docker Desktop: 

`2023-04-03 18:07:04 marquez-db   | 2023-04-03 23:07:04.726 GMT [35] FATAL:  password authentication failed for user "marquez"
2023-04-03 18:07:04 marquez-db   | 2023-04-03 23:07:04.726 GMT [35] DETAIL:  Role "marquez" does not exist.`

and

`ERROR [2023-04-03 22:44:31,217] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
2023-04-03 17:44:31 ! org.postgresql.util.PSQLException: FATAL: password authentication failed for user "marquez"`

All the steps in the README.md file were used to configure the PostgreSQL database for Marquez and to set the correct environment variables. 
During my trouble shooting practices, I found a relatively similar issue on StackOverflow which refers to the danger in using the same ports for Postgres and Marquez but this did not help me yet in solving the issue (https://stackoverflow.com/questions/62115827/org-postgresql-util-psqlexception-fatal-password-authentication-failed-for-use).

Could you please help me out? 

Kind regards, 

Tom

**Comment by rossturk** [comment]
That looks to me like the database volumes haven't been created.

I would recommend trying  `docker/up.sh --noweb` to accomplish this. That script does some preparation tasks (which you can see inside `docker/volumes.sh` if you want to replicate them) and then calls `docker-compose` to bring everything up.

The prep steps you are following in `README.md` are, I believe, for running outside of Docker.

**Comment by TomEijk** [comment]
Thank you so much for your reply Ross! 

Unfortunately, the logs in Docker Desktop still return the same error when I use `docker/up.sh --no-web`. 
I guess it has to do something with my PostgreSQL database. These are the steps how I try to get the Marquez API image running: 

1. Create an on-premise PostgreSQL connection with server `marquez`, database `marquez`, user `marquez` and port `5433` (to not have my PostgreSQL database and Marquez docker container on the same port)
2. Build the project in my IDE via `./gradlew build` in the `marquez` directory.
3. Set the following environment variables in my IDE: POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD, and POSTGRES_PORT (to 5433).  
4. Run the `docker/up.sh --no-web` in the `marquez` directory.

The strange thing here is that even when I use `$Env:POSTGRES_USER='test'`, the Docker Desktop logs return this error: 
`ERROR [2023-04-03 22:44:31,217] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool. 2023-04-03 17:44:31 ! org.postgresql.util.PSQLException: FATAL: password authentication failed for user "marquez"`

So perhaps there is something hard coded? Changing the environment variables does not seem to have any effect. 

Kind regards, 

Tom

**Comment by TomEijk** [comment]
After some trial and error, I noticed the code does not completely run in Git Bash which means the error actually happens even further upstream. It returns: 

`the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'`.

I guess this means the volumes haven't been created indeed (so scripts like `init-db.sh` probably didn't run either which could explain the Marquez authentication error). 
Tried several things already to adjust the `./bashrc` file but it still returns the error. 
Let me please know if anyone has a solution for this.

Kind regards, 

Tom

**Comment by NavneetSajwan** [comment]
I am experiencing the same issue

**Comment by schandir** [comment]
@TomEijk @NavneetSajwan @genegc , I had similar issue and I fixed it by setting the default values for postgres server as localhost in the file 'marquez\marquez.dev.yml'
![image](https://github.com/user-attachments/assets/29291ee7-de1f-44e7-9561-d9658e695c4a)

Let me know if that works for you and I can raise a PR

**Comment by wslulciuc** [comment]
Fixed by @schandir in https://github.com/MarquezProject/marquez/pull/2959 🙌
