### ISSUE TITLE
Failed to pull image "docker.io/bitnami/postgresql:0.33.0"

### ISSUE THREAD

**Issue by andreyolv** [MarquezProject/marquez#2479]
postgresql pod does not run

  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  4m11s                 default-scheduler  Successfully assigned marquez/marquez-postgresql-0 to platform-k8s-worker2
  Normal   Pulling    111s (x4 over 4m10s)  kubelet            Pulling image "docker.io/bitnami/postgresql:0.33.0"
  Warning  Failed     109s (x4 over 3m15s)  kubelet            Failed to pull image "docker.io/bitnami/postgresql:0.33.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/bitnami/postgresql:0.33.0": failed to resolve reference "docker.io/bitnami/postgresql:0.33.0": docker.io/bitnami/postgresql:0.33.0: not found
  Warning  Failed     109s (x4 over 3m15s)  kubelet            Error: ErrImagePull
  Warning  Failed     98s (x6 over 3m14s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    85s (x7 over 3m14s)   kubelet            Back-off pulling image "docker.io/bitnami/postgresql:0.33.0"

**Comment by wslulciuc** [comment]
@andreyolv: yeah this was a very very annoying bug in our release script that has been fixed in https://github.com/MarquezProject/marquez/pull/2488
