### ISSUE TITLE
Marquez can't display 2 outputs dataset for the same job

### ISSUE THREAD

**Issue by dkt-sophie-ly** [MarquezProject/marquez#2492]
Hello ! 

I have a really simple job which take 2 datasets (input1 and input2) and create 2 files (output1 and output2), basically we can schematize it like this:

input1 --- job_x ---> output1

input2 --- job_x ---> output2

I expect a similar lineage in marquez but i only have the lineage for input2 --- job_x ---> output2 and input1 and output2 are considered as dataset but they are not linked by any job.

![image](https://github.com/MarquezProject/marquez/assets/130998593/d04583df-f770-492a-86a8-403cf8c6be0b)

![image](https://github.com/MarquezProject/marquez/assets/130998593/0db16be2-de7d-45a2-875e-149856856062)

I feel like marquez can't support several outputs for a job, is it expected or is it a bug ? 

Event for input1:

`
{
  "job": {
    "name": "issue_job.execute_insert_into_hadoop_fs_relation_command",
    "facets": {},
    "namespace": "spark_integration"
  },
  "run": {
    "runId": "8650aef3-dfac-4f35-843f-0f9e3368a248",
    "facets": {
      "spark_version": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
        "_schemaURL": "https://openlineage.io/spec/1-0-5/OpenLineage.json#/$defs/RunFacet",
        "spark-version": "3.3.2",
        "openlineage-spark-version": "0.26.0"
      },
      "spark.logicalPlan": {
        "plan": [
          {
            "class": "org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand",
            "query": 0,
            "num-children": 1,
            "partitionColumns": [],
            "outputColumnNames": "[data1, data2]",
            "ifPartitionNotExists": false
          },
          {
            "class": "org.apache.spark.sql.catalyst.plans.logical.Union",
            "byName": false,
            "children": [
              0,
              1
            ],
            "num-children": 2,
            "allowMissingCol": false
          },
          {
            "class": "org.apache.spark.sql.execution.datasources.LogicalRelation",
            "output": [
              [
                {
                  "name": "data1",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 17,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "string",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "data2",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 18,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "string",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ]
            ],
            "isStreaming": false,
            "num-children": 0
          },
          {
            "child": 0,
            "class": "org.apache.spark.sql.catalyst.plans.logical.Project",
            "projectList": [
              [
                {
                  "name": "_1",
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Alias",
                  "exprId": {
                    "id": 48,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "qualifier": [],
                  "num-children": 1,
                  "nonInheritableMetadataKeys": []
                },
                {
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Cast",
                  "dataType": "string",
                  "timeZoneId": "UTC",
                  "ansiEnabled": false,
                  "num-children": 1
                },
                {
                  "name": "_1",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 44,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "_2",
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Alias",
                  "exprId": {
                    "id": 49,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "qualifier": [],
                  "num-children": 1,
                  "nonInheritableMetadataKeys": []
                },
                {
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Cast",
                  "dataType": "string",
                  "timeZoneId": "UTC",
                  "ansiEnabled": false,
                  "num-children": 1
                },
                {
                  "name": "_2",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 45,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ]
            ],
            "num-children": 1
          },
          {
            "class": "org.apache.spark.sql.execution.LogicalRDD",
            "output": [
              [
                {
                  "name": "_1",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 44,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "_2",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 45,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ]
            ],
            "isStreaming": false,
            "num-children": 0,
            "outputOrdering": [],
            "outputPartitioning": {
              "numPartitions": 0,
              "product-class": "org.apache.spark.sql.catalyst.plans.physical.UnknownPartitioning"
            }
          }
        ],
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
        "_schemaURL": "https://openlineage.io/spec/1-0-5/OpenLineage.json#/$defs/RunFacet"
      }
    }
  },
  "inputs": [
    {
      "name": "/usr/local/airflow/data_test_issue/data1.csv",
      "facets": {
        "schema": {
          "fields": [
            {
              "name": "data1",
              "type": "string"
            },
            {
              "name": "data2",
              "type": "string"
            }
          ],
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet"
        },
        "dataSource": {
          "uri": "file",
          "name": "file",
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet"
        }
      },
      "namespace": "file",
      "inputFacets": {}
    }
  ],
  "outputs": [
    {
      "name": "/usr/local/airflow/data/output/output1.csv",
      "facets": {
        "schema": {
          "fields": [
            {
              "name": "data1",
              "type": "string"
            },
            {
              "name": "data2",
              "type": "string"
            }
          ],
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet"
        },
        "dataSource": {
          "uri": "file",
          "name": "file",
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet"
        },
        "columnLineage": {
          "fields": {
            "data1": {
              "inputFields": [
                {
                  "name": "/usr/local/airflow/data_test_issue/data1.csv",
                  "field": "data1",
                  "namespace": "file"
                }
              ]
            },
            "data2": {
              "inputFields": [
                {
                  "name": "/usr/local/airflow/data_test_issue/data1.csv",
                  "field": "data2",
                  "namespace": "file"
                }
              ]
            }
          },
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/ColumnLineageDatasetFacet.json#/$defs/ColumnLineageDatasetFacet"
        },
        "lifecycleStateChange": {
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/LifecycleStateChangeDatasetFacet.json#/$defs/LifecycleStateChangeDatasetFacet",
          "lifecycleStateChange": "OVERWRITE"
        }
      },
      "namespace": "file",
      "outputFacets": {}
    }
  ],
  "producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
  "eventTime": "2023-05-25T13:27:07.694Z",
  "eventType": "START",
  "schemaURL": "https://openlineage.io/spec/1-0-5/OpenLineage.json#/$defs/RunEvent"
}
`

Event for input2:

`
{
  "job": {
    "name": "issue_job.execute_insert_into_hadoop_fs_relation_command",
    "facets": {},
    "namespace": "spark_integration"
  },
  "run": {
    "runId": "78a63d3b-1a50-4488-aa9a-5e1251d57812",
    "facets": {
      "spark_version": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
        "_schemaURL": "https://openlineage.io/spec/1-0-5/OpenLineage.json#/$defs/RunFacet",
        "spark-version": "3.3.2",
        "openlineage-spark-version": "0.26.0"
      },
      "spark.logicalPlan": {
        "plan": [
          {
            "class": "org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand",
            "query": 0,
            "num-children": 1,
            "partitionColumns": [],
            "outputColumnNames": "[col1, col2, col3]",
            "ifPartitionNotExists": false
          },
          {
            "class": "org.apache.spark.sql.catalyst.plans.logical.Union",
            "byName": false,
            "children": [
              0,
              1
            ],
            "num-children": 2,
            "allowMissingCol": false
          },
          {
            "class": "org.apache.spark.sql.execution.datasources.LogicalRelation",
            "output": [
              [
                {
                  "name": "col1",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 38,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "string",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "col2",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 39,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "string",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "col3",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 40,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "string",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ]
            ],
            "isStreaming": false,
            "num-children": 0
          },
          {
            "child": 0,
            "class": "org.apache.spark.sql.catalyst.plans.logical.Project",
            "projectList": [
              [
                {
                  "name": "_1",
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Alias",
                  "exprId": {
                    "id": 58,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "qualifier": [],
                  "num-children": 1,
                  "nonInheritableMetadataKeys": []
                },
                {
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Cast",
                  "dataType": "string",
                  "timeZoneId": "UTC",
                  "ansiEnabled": false,
                  "num-children": 1
                },
                {
                  "name": "_1",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 52,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "_2",
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Alias",
                  "exprId": {
                    "id": 59,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "qualifier": [],
                  "num-children": 1,
                  "nonInheritableMetadataKeys": []
                },
                {
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Cast",
                  "dataType": "string",
                  "timeZoneId": "UTC",
                  "ansiEnabled": false,
                  "num-children": 1
                },
                {
                  "name": "_2",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 53,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "_3",
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Alias",
                  "exprId": {
                    "id": 60,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "qualifier": [],
                  "num-children": 1,
                  "nonInheritableMetadataKeys": []
                },
                {
                  "child": 0,
                  "class": "org.apache.spark.sql.catalyst.expressions.Cast",
                  "dataType": "string",
                  "timeZoneId": "UTC",
                  "ansiEnabled": false,
                  "num-children": 1
                },
                {
                  "name": "_3",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 54,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ]
            ],
            "num-children": 1
          },
          {
            "class": "org.apache.spark.sql.execution.LogicalRDD",
            "output": [
              [
                {
                  "name": "_1",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 52,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "_2",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 53,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ],
              [
                {
                  "name": "_3",
                  "class": "org.apache.spark.sql.catalyst.expressions.AttributeReference",
                  "exprId": {
                    "id": 54,
                    "jvmId": "c90f36a1-263f-4958-83f0-acb592674dfb",
                    "product-class": "org.apache.spark.sql.catalyst.expressions.ExprId"
                  },
                  "dataType": "long",
                  "metadata": {},
                  "nullable": true,
                  "qualifier": [],
                  "num-children": 0
                }
              ]
            ],
            "isStreaming": false,
            "num-children": 0,
            "outputOrdering": [],
            "outputPartitioning": {
              "numPartitions": 0,
              "product-class": "org.apache.spark.sql.catalyst.plans.physical.UnknownPartitioning"
            }
          }
        ],
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
        "_schemaURL": "https://openlineage.io/spec/1-0-5/OpenLineage.json#/$defs/RunFacet"
      }
    }
  },
  "inputs": [
    {
      "name": "/usr/local/airflow/data_test_issue/data2.csv",
      "facets": {
        "schema": {
          "fields": [
            {
              "name": "col1",
              "type": "string"
            },
            {
              "name": "col2",
              "type": "string"
            },
            {
              "name": "col3",
              "type": "string"
            }
          ],
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet"
        },
        "dataSource": {
          "uri": "file",
          "name": "file",
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet"
        }
      },
      "namespace": "file",
      "inputFacets": {}
    }
  ],
  "outputs": [
    {
      "name": "/usr/local/airflow/data/output/output2.csv",
      "facets": {
        "schema": {
          "fields": [
            {
              "name": "col1",
              "type": "string"
            },
            {
              "name": "col2",
              "type": "string"
            },
            {
              "name": "col3",
              "type": "string"
            }
          ],
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet"
        },
        "dataSource": {
          "uri": "file",
          "name": "file",
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet"
        },
        "columnLineage": {
          "fields": {
            "col1": {
              "inputFields": [
                {
                  "name": "/usr/local/airflow/data_test_issue/data2.csv",
                  "field": "col1",
                  "namespace": "file"
                }
              ]
            },
            "col2": {
              "inputFields": [
                {
                  "name": "/usr/local/airflow/data_test_issue/data2.csv",
                  "field": "col2",
                  "namespace": "file"
                }
              ]
            },
            "col3": {
              "inputFields": [
                {
                  "name": "/usr/local/airflow/data_test_issue/data2.csv",
                  "field": "col3",
                  "namespace": "file"
                }
              ]
            }
          },
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/ColumnLineageDatasetFacet.json#/$defs/ColumnLineageDatasetFacet"
        },
        "lifecycleStateChange": {
          "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
          "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/LifecycleStateChangeDatasetFacet.json#/$defs/LifecycleStateChangeDatasetFacet",
          "lifecycleStateChange": "OVERWRITE"
        }
      },
      "namespace": "file",
      "outputFacets": {}
    }
  ],
  "producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/spark",
  "eventTime": "2023-05-25T13:27:10.286Z",
  "eventType": "COMPLETE",
  "schemaURL": "https://openlineage.io/spec/1-0-5/OpenLineage.json#/$defs/RunEvent"
}
`

job_x is a pyspark script that generate event with open_lineage:

`
    spark = SparkSession.builder \
        .appName("issue_job") \
        .master("local") \
        .config("spark.jars.packages", "io.openlineage:openlineage-spark:0.26.0") \
        .config("spark.jars.packages", "io.delta: delta-core_2.12:2.1.0") \
        .config("spark.openlineage.host", "http://marquez:5000") \
        .config("spark.openlineage.transport.type", "http") \
        .config("spark.openlineage.transport.url", "http://marquez:5000/") \
        .config("spark.openlineage.namespace", "spark_integration") \
        .config("spark.extraListeners", "io.openlineage.spark.agent.OpenLineageSparkListener") \
        .getOrCreate()

    # Read the input CSV file from the MinIO bucket
    df1 = spark.read.csv('/usr/local/airflow/data_test_issue/data1.csv', header=True)
    df2 = spark.read.csv('/usr/local/airflow/data_test_issue/data2.csv', header=True)

    # Add a new row for data1
    new_data = [[4, 4]]
    tmp_df = spark.createDataFrame(new_data)
    df1 = df1.union(tmp_df)

    # Add a new row for data2
    new_data = [[4, 4, 4]]
    tmp_df = spark.createDataFrame(new_data)
    df2 = df2.union(tmp_df)

    # Save the file
    df1.write.option("header", "true").csv("/usr/local/airflow/data/output/output1.csv", mode="overwrite")
    df2.write.option("header", "true").csv("/usr/local/airflow/data/output/output2.csv", mode="overwrite")

    # Stop the Spark session
    spark.stop()
`

**Comment by Bisceto** [comment]
Hi @dkt-sophie-ly, you're not alone in this. I have a Spark job that writes to 2 different outputs. However, only the lineage for one of the outputs can be seen in Marquez. After more testing, I suspect that it has to do with the `execute_insert_into_hadoop_fs_relation_command` being overwritten when Marquez is tracking the lineage. 

For instance, when this piece of code in my Spark job is run:
```
result1.write.mode("overwrite").parquet("file:///usr/local/spark/app/output/result1.parquet")
result2.write.mode("overwrite").parquet("file:///usr/local/spark/app/output/result2.parquet")
```
The lineage is shown for result2 but not result1. The reverse happens when I flip the order of the code.

Hope the Marquez devs can update whether this is an intended effect or a bug!

**Comment by dkt-sophie-ly** [comment]
Hi ! @pawel-big-lebowski @wslulciuc do you have any updates on this issue ? 
Is it a bug or a intended behavior ?

Thanks for your help !

**Comment by dkt-sophie-ly** [comment]
Hi ! 

I tested this issue with open-lineage 1.4.1 and it seems that it has been resolved.

Test scenario:
```
df = spark.read.format("delta").load('s3://bucket/data')
df_col_1 = df.select("col1")
df_col_2 = df.select("col2")

# Save the file
df_col_1.write.mode("overwrite").parquet("s3://bucket/output/df_col_1")
df_col_2.write.mode("overwrite").parquet("s3://bucket/output/df_col_2")
```

Lineage:

![image](https://github.com/MarquezProject/marquez/assets/130998593/0abbe384-ddd1-4613-a4e2-b3f22dc7c990)


So i'm closing this issue :)
