### ISSUE TITLE
Feature based package structure vs layer based

### ISSUE THREAD

**Issue by lulciuca** [MarquezProject/marquez#25]
For better cohesiveness and manageability, I think we should move to a feature based package structure over the current layer based. I've created a branch as an example.

https://github.com/lulciuca/marquez/tree/feature-based-package-structure

Here's a nice article on the subject: http://www.javapractices.com/topic/TopicAction.do?Id=205

**Comment by wslulciuc** [comment]
The linked article helped and was a nice read. Perhaps the _feature-based package_ approach might make sense in the future and we can refactor if that's the case. But for now, our [API model](https://www.lucidchart.com/documents/edit/f918ce01-9eb4-4900-b266-49935da271b8/0) is small enough where it's manageable and don't foresee many additions to the core models we already have defined.

**Comment by lulciuca** [comment]
Sounds good.
