### ISSUE TITLE
Slack shared-link on https://marquezproject.ai/ doesn't work

### ISSUE THREAD

**Issue by Xavier-Cliquennois** [MarquezProject/marquez#2533]
On the website, the Slack CTA redirects to "https://marquezproject.slack.com/join/shared_invite/zt-linj7k52-NaYvdVsa7SkR5T4IMMzZFw#/shared-invite/error", making it impossible to join your Slack without a manual invitation.

Additionally, the tiny URL "http://bit.ly/MqzSlack" does not lead to a shared invitation, rendering it unusable for joining your Slack as well.

**Comment by wslulciuc** [comment]
@merobi-hub, can we confirm that the URL [http://bit.ly/MqzSlack](http://bit.ly/MqzSlack) redirects to a valid invitation?

**Comment by wslulciuc** [comment]
@Xavier-Cliquennois, you can now join our channel via the link [https://bit.ly/MqzSlackInvite](https://bit.ly/MqzSlackInvite)! Thanks for letting us know about the slack invite issue, see you there!
