### ISSUE TITLE
Potential Bug with Circle CI Build api-load-test.sh

### ISSUE THREAD

**Issue by davidsharp7** [MarquezProject/marquez#2743]
On a recent build I have got this error

```
>> start load test:
./.circleci/api-load-test.sh: line 107: k6: command not found

Exited with code exit status 127
```

think it relates to this code in the script

```
mkdir -p k6/results && \
  k6 run --vus 25 --duration 30s api/load-testing/http.js \
    --out json=k6/results/full.json --summary-export=k6/results/summary.json
```

As a consequence the build is failing.  Not sure if this is impacting other people.

**Comment by wslulciuc** [comment]
Odd, our recent CI build for main is [passing](https://app.circleci.com/pipelines/github/MarquezProject/marquez/11430/workflows/8a1012fc-21c5-4cdc-a889-dc8bb4b1fb82/jobs/86015). Can you link to your CI job for your branch?

**Comment by davidsharp7** [comment]
Yeah just looking at the logs your main run is using a different image

[Main](https://app.circleci.com/pipelines/github/MarquezProject/marquez/11430/workflows/8a1012fc-21c5-4cdc-a889-dc8bb4b1fb82/jobs/86015)

```
machine-agent version 1.0.69270-30518a2 (image: "ubuntu-2004:2023.10.1", public ip: "54.85.73.221", provider: "EC2")
```

[PR2729](https://app.circleci.com/pipelines/github/MarquezProject/marquez/11451/workflows/d59e54ee-0509-4171-ad10-563580cf47aa/jobs/86139)

```
machine-agent version 1.0.69699-fdc5c0d (image: "ubuntu-2004:2024.01.2", public ip: "54.221.153.200", provider: "EC2")
```

Shouldn't be an issue but that is the only difference I can see.
