### ISSUE TITLE
Add `Tag` support for `Job`s

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#2756]
We currently support tagging datasets and fields, but we should also expand support to include tagging jobs. For example, we have the job types `BATCH `, `STREAM`, `SERVICE` and some tags could include:
* `WEEKLY`, `DAILY` (relates to scheduling)
* `SPARK `, `AIRFLOW`  (relates runtime execution)

**Comment by davidsharp7** [comment]
So we would need an additional table to capture the mapping - something like

![image](https://github.com/MarquezProject/marquez/assets/34074888/3de68396-faf8-4880-9c5e-9e61273f1b08)

and a couple of end points

POST http://localhost:5000/api/v1/namespaces/{namespace}/jobs/{job}/tags/{tag}
DELETE http://localhost:5000/api/v1/namespaces/{namespace}/jobs/{job}/tags/{tag}

@wslulciuc - can you think of anything else we might need (excluding UI changes)
