### ISSUE TITLE
Web UI does not show Job facets

### ISSUE THREAD

**Issue by agaro1121** [MarquezProject/marquez#2773]
re: https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.md#job-facets

The web-ui currently does not have a central location to display all of the job facets.  Some of the job facets are sprinkled into the UI in various forms.

For example, 

[SQLJobFacet](https://github.com/OpenLineage/OpenLineage/blob/main/spec/facets/SQLJobFacet.json) is added to the latest  [RunInfo component](https://github.com/MarquezProject/marquez/blob/main/web/src/components/jobs/RunInfo.tsx#L55)

[SourceCodeLocationJobFacet](https://github.com/OpenLineage/OpenLineage/blob/main/spec/facets/SourceCodeLocationJobFacet.json) is displayed as a [button](https://github.com/MarquezProject/marquez/blob/main/web/src/components/jobs/JobDetailPage.tsx#L152) on the `JobDetailsPlage`. The button gets disabled when the facet was not sent as part of the lineage event. This is not immediately obvious.

I came across this when I sent `ownership` as a job facet but could not find it anywhere in the UI. I edited the code locally and was able to display the facets but I realized the `JobDetailsPage` doesn't actually have a tab for job details. It shows the latest run in the first tab and it makes sense that the run facets are the ones displayed there, not the job facets.

Documentation on this behavior would be helpful to the users as this is not immediately obvious.  Perhaps the UI can gain a new tab to show this static job information in the future as well.

Please note: The web module requests all the facets so it's a matter of displaying the data. The code does not need to be updated to fetch any new information.

**Comment by davidsharp7** [comment]
@wslulciuc @phixMe  - I am guessing I will need to add the jobs tag to this at some point so happy to put together some ideas for this.

**Comment by phixMe** [comment]
Hey @agaro1121, Our interface is undergoing a bit of a renaissance right now and we want to add as much as we can. Is this something you could contribute? The file for this is located here: https://github.com/MarquezProject/marquez/blob/main/web/src/components/jobs/JobDetailPage.tsx

**Comment by phixMe** [comment]
@agaro1121 I think we're in a better place here now... The page now dumps out all of the facets. If there is something in particular we wish to render, let us know and add I can get a PR up quickly!

<img width="793" alt="image" src="https://github.com/user-attachments/assets/e0c06066-3922-41f1-abeb-2bd507a81bd4">
