### ISSUE TITLE
Web UI error - Module not found

### ISSUE THREAD

**Issue by protokoul** [MarquezProject/marquez#2827]
I have followed the steps [here](https://github.com/MarquezProject/marquez/tree/main/web#development) to run the web UI. I am running node v18.20.3 on Windows using nvm on gitbash. I was able to install the dependencies and after trying to start the UI, I get this error

![image](https://github.com/MarquezProject/marquez/assets/6755025/bbf73d1c-8d7c-4791-9009-99c1e6a494e0)

**Comment by wslulciuc** [comment]
@phixMe, thoughts?

**Comment by phixMe** [comment]
Hmm, It looks like this could possibly be a relative import pathing issue in the webpack config. Is there a setting that you can change to rectify this the `webpack.dev.js` file. (And the other corresponding webpack files)

I cannot recreate this myself on my Mac, but perhaps we need something like this instead:

```js 
entry: path.resolve(__dirname, './src/index.tsx'),
```

Anyways, @protokoul if you could try a few local debugging steps out yourself and potentially contribute your findings that would be much appreciated.

**Comment by protokoul** [comment]
I ran this command `npm install history` and then ran the dev server. It worked. Maybe having only the type definitions (@types/history) without the actual package can cause issues?

**Comment by phixMe** [comment]
I'm going to close this because it appears that there has been a resolution and I haven't seen any more reports.
