### ISSUE TITLE
Fix lines longer than 100 chars 

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#283]
```
$ ./gradlew checkstyleMain checkstyleTest

[ant:checkstyle] [WARN] /Users/willy.lulciuc/dev/marquezproject/marquez/src/test/java/marquez/api/JobIntegrationTest.java:300: Line is longer than 100 characters (found 196). [LineLength]
[ant:checkstyle] [WARN] /Users/willy.lulciuc/dev/marquezproject/marquez/src/test/java/marquez/db/NamespaceDaoTest.java:44: Line is longer than 100 characters (found 108). [LineLength]
...

**Comment by hjpatel16** [comment]
Hey, Can I work on it?

**Comment by wslulciuc** [comment]
Sure! Thanks, @hjpatel16

**Comment by pbrahmbhatt3** [comment]
can i work on it?

**Comment by wslulciuc** [comment]
Hey, @pbrahmbhatt3. I believe @hjpatel16 wanted to tackle this issue. But, not sure of the progress. Would be great to get an update from @hjpatel16 before reassigned the issue :)

**Comment by wslulciuc** [comment]
@pbrahmbhatt3: Would you still like to work on this issue? Happy to reassign it to you.

**Comment by priyankalakhe** [comment]
@wslulciuc  - I can work on this, if you are still looking for someone to take this up.

**Comment by wslulciuc** [comment]
Yes! Thanks for your help, @priyankalakhe

**Comment by priyankalakhe** [comment]
Hi @wslulciuc  - looks like this was deleted as part of https://github.com/MarquezProject/marquez/commit/372013ae53cf8ed799d0dca075a675e943e99e2e

**Comment by wslulciuc** [comment]
Yeah, the codebase has gone though some refactoring. Meaning, classes have been added or removed. If there aren’t any warnings around line length, we can close the issue.

**Comment by wslulciuc** [comment]
@priyankalakhe, closing this issue for now. Thanks for looking into it!
