### ISSUE TITLE
Web UI - quality display

### ISSUE THREAD

**Issue by namyyys** [MarquezProject/marquez#2839]
Quality is deemed as unhealthy but the text is displayed in green instead of red. 

![Capture d’écran 2024-06-21 à 16 45 26](https://github.com/MarquezProject/marquez/assets/147636230/ec145062-6909-4767-a320-bf13f7a1ec79)

**Comment by phixMe** [comment]
Can you dig into the root cause of this a little for us and evaluate our conditional logic along with the OpenLineage events that you have defined?

The logic we have for this lies here:
https://github.com/MarquezProject/marquez/blob/main/web/src/routes/datasets/Datasets.tsx#L219-L230

**Comment by namyyys** [comment]
I tried to dig into the root cause a little bit. From my analysis i think it's coming from [this function](https://github.com/MarquezProject/marquez/blob/main/web/src/helpers/nodes.ts#L117-L134)
We encounter this issue with a dataset, for example, which has 34 assertions (32 passing and 2 failing). In the logic i see from the above function, the color of the quality is only tested on a subset of all the assertions (the last 14 i believe). We think that the 2 failing cases are not included in this subset and thus the coloring is wrong.

**Comment by phixMe** [comment]
Yes, thanks, I just submitted a PR to rectify this.
