### ISSUE TITLE
Fix abbreviation in name

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#284]
```
$ ./gradlew checkstyleMain checkstyleTest

[ant:checkstyle] [WARN] /Users/willy.lulciuc/dev/marquezproject/marquez/src/test/java/marquez/api/JobRunResponseTest.java:80: Abbreviation in name 'testJobRunInequalityOnNonIDField' must contain no more than '2' consecutive capital letters. [AbbreviationAsWordInName]
[ant:checkstyle] [WARN] /Users/willy.lulciuc/dev/marquezproject/marquez/src/test/java/marquez/api/JobTest.java:43: Abbreviation in name 'testJobInequalityOnNonIDField' must contain no more than '2' consecutive capital letters. [AbbreviationAsWordInName]
...
```

**Comment by hjpatel16** [comment]
Hey, Can I work on it?

**Comment by wslulciuc** [comment]
Sure! Thanks, @hjpatel16

**Comment by priyankalakhe** [comment]
@wslulciuc  - I can work on this, if you are still looking for someone to take this up.

**Comment by wslulciuc** [comment]
Yes! Thanks for your help, @priyankalakhe

**Comment by priyankalakhe** [comment]
@wslulciuc  - 
I cannot find the files mentioned in this issue in the project anymore. 

There are other checkstyle violations to be sure, just not the ones mentioned in this issue for the classes mentioned in this issue. 

<img width="659" alt="Screen Shot 2019-10-26 at 12 51 51 AM" src="https://user-images.githubusercontent.com/4805758/67616204-d144b800-f78a-11e9-8d87-43bdabe13296.png">
<img width="659" alt="Screen Shot 2019-10-26 at 12 51 40 AM" src="https://user-images.githubusercontent.com/4805758/67616205-d30e7b80-f78a-11e9-8605-3fe08b463bd7.png">
