### ISSUE TITLE
Web UI - version history

### ISSUE THREAD

**Issue by namyyys** [MarquezProject/marquez#2840]
Version history displays the same version multiple times 

![Capture d’écran 2024-06-21 à 17 02 20](https://github.com/MarquezProject/marquez/assets/147636230/5de71701-56cc-45d8-8d1c-47871f1d8737)

**Comment by phixMe** [comment]
Is this because the same OL event was posted a couple of times?

**Comment by namyyys** [comment]
After investigating a little bit more about this problem i realized that it was due to the symlinks (We are seeing as many versions as there are symlinks). This seems to be a feature so this issue can be closed
