### ISSUE TITLE
zoom and pan not working locally

### ISSUE THREAD

**Issue by merobi-hub** [MarquezProject/marquez#2845]
All zoom and pan tools seem not to be working when running Marquez locally, either in a container on the latest version or on a dev server from `main`. There is no difference if containers are run on Docker Desktop or Colima. Question: is functionality intentionally disabled for small graphs (around 4 nodes)? (If so, perhaps this should be documented, or the tools should be hidden for small graphs.)

OS: MacOS Sonoma 14.5
Marquez web versions: `0.47.0`, `main`
Arch: Aarch64
Browsers: Chrome, Safari

See attachment for an error in ZoomPanSvg.tsx logged in Chrome (couldn't copy and paste it):
 
<img width="1434" alt="Screenshot 2024-06-30 at 14 59 38" src="https://github.com/MarquezProject/marquez/assets/68482867/767c62ad-04e4-4061-99a0-ffa073a1f9e7">

**Comment by phixMe** [comment]
I think this is working as intended for small graphs where users are restricted from moving and panning around since it would not serve them or help gain any information. I think we could disable this if it's a confusing behavior, but I think it's not quite required.
