### ISSUE TITLE
[UI] When an error is displayed on the UI, the error message will remain on the screen even after several action that doesn't raise errors

### ISSUE THREAD

**Issue by dkt-sophie-ly** [MarquezProject/marquez#2888]
Sometime when marquez API return 400 or 500 errors the UI will display an error like that for example:

![image](https://github.com/user-attachments/assets/c2d069ef-1ffe-4377-8886-96e61d304f97)

But if I click on something else (another page not related to the first error) the error (the yellow box) will still remain on the UI until the page is refreshed:

Ex: job run
![image](https://github.com/user-attachments/assets/82049694-34d9-43f5-b7a3-966fc0280881)

In order to make this error disappear from the screen we need to refresh the page but it's not very convenient and may be confusing for the users.
Can we display the error only on the page that trigger this error ? And not on all page afterwards ?

**Comment by phixMe** [comment]
I'll get this fixed for you right now, this is from many years ago, and never got fixed.
