### ISSUE TITLE
Define gradle task to run unit tests only

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#293]
Let's define a gradle task to run unit tests only leveraging the category define in #292

**Comment by ashulmanWeWork** [comment]
Should be something like this: 
```
test {
    useJUnit {
        includeCategories 'org.gradle.junit.CategoryA'
        excludeCategories 'org.gradle.junit.CategoryB'
    }
}
```

**Comment by wslulciuc** [comment]
Yep. Though it seems `excludeCategories` is optional : https://github.com/MarquezProject/marquez/blob/update-common-models/build.gradle#L43
