### ISSUE TITLE
[Question] - Can lineage data in marquez be exported in open lineage format

### ISSUE THREAD

**Issue by TejasRGitHub** [MarquezProject/marquez#2970]
Hi Team, 

Is there a way in the UI or with the API with which I can export all the lineage data from Marquez ?

**Comment by phixMe** [comment]
The data is all captured within the `lineage_events` table... You could theoretically wipe the data in every other table (although there are a bunch of foreign keys that prevent unilateral drops) and replay events captured in the `lineage_events` table.

Also, in the User Interface, there is an events page that renders the entirety of the payload if you wanted to use that... There is a corresponding api that is queried by this page that takes date bounds.
