### ISSUE TITLE
Regression `docker/up.sh -d` conflicts between `--detach` and `--db-port`

### ISSUE THREAD

**Issue by sj-ganwh** [MarquezProject/marquez#2975]
Blame:
![image](https://github.com/user-attachments/assets/1d9314b7-e63c-4e8c-b313-9380c7abe92c)

Execute output:
![image](https://github.com/user-attachments/assets/c719489b-fb5d-40d6-9fbb-e8cf0be95f5a)

**Comment by wslulciuc** [comment]
Thanks for opening this issue, @sj-ganwh! Since this was a regression I introduced, I feel like it's on me to fix it: see https://github.com/MarquezProject/marquez/pull/2977
