### ISSUE TITLE
Update model mappers

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#301]
Let's update _all_ of our model mappers to:

* Be immutable and define the class as **final**
* Define constructor as **private**
* Define one or more `B map(A)` static methods for the mapper type `B`

## Issues

- [x] Add JobMapper #296
- [x] Add JobResponseMapper #297
- [x] Add JobRunMapper #298
- [x] Add JobRunResponseMapper #299
- [x] Add NamespaceMapper #300
- [x] Add DatasetMapper #302

**Comment by DavidLi119** [comment]
Hi I would like to work on the file NamespaceApiMapper.java and update the model mapper

**Comment by wslulciuc** [comment]
Hey, @DavidLi119! Sure, did you want to pick up issue #300?

**Note:** `NamespaceApiMapper` is a legacy class and will be replaced by `NamespaceMapper`

**Comment by DavidLi119** [comment]
If possible I would, please. What exactly do I have to do?

**Comment by wslulciuc** [comment]
Happy to help. The epic description (above) outlines the required changes. What part would you like me to provide more details on?

**Comment by DavidLi119** [comment]
Do I replace NamespaceApiMapper with NamespaceMapper with changes? or do I create a separate file in the same location?

**Comment by wslulciuc** [comment]
Let's create a separate class. I want to deprecate `NamespaceApiMapper` and replace it with `NamespaceMapper`. A great example to model you class after would be: [`DbTableVersionMapper`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/mappers/DbTableVersionMapper.java)

**Comment by wslulciuc** [comment]
For context, **Mappers** convert objects with different structure and concerns between layers (`api`, `service`, `db`) by mapping one object to another. The class `NamespaceMapper` maps a [`NamespaceRequest`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/models/NamespaceRequest.java) to [`Namespace`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/models/Namespace.java).

Let me know if this is helpful, @DavidLi119.

**Comment by wslulciuc** [comment]
Fixed #627
