### ISSUE TITLE
Add JobResponseMapper.toJobsResponse()

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#307]
Returns an instance of [`JobsResponse`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/models/JobsResponse.java).

**NOTE:** For a great example mapper, see [`DatasetResponseMapper.toDatasetsResponse()`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/mappers/DatasetResponseMapper.java#L43)

**Comment by hjpatel16** [comment]
@wslulciuc Isn't this already implemented?

**Comment by wslulciuc** [comment]
@hjpatel16: The class [`api.mappers.JobResponseMapper`](https://github.com/MarquezProject/marquez/tree/master/src/main/java/marquez/api/mappers) still needs to be implemented. We do have mappers that are used in [`JobResource`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/resources/JobResource.java), but we are moving away from using [`Mapper`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/mappers/Mapper.java) in favoring of defining mappers as helpers with on or more static `map()` methods. For an example, see [`DatasetResponseMapper`](https://github.com/MarquezProject/marquez/blob/feature/dataset-resource-create-get-ops/src/main/java/marquez/api/mappers/DatasetResponseMapper.java). If this is something you wanted to work on, let us know! We can provide more details around the issue.

**Comment by wslulciuc** [comment]
Fixed #503
