### ISSUE TITLE
Default column value to null when description not present

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#311]
We currently default the description column for `Namespace`, `Job`, `Dataset`, etc  to an empty string (`""`).  Let's use `null` instead to signify an unknown or not given description. 

see: https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/common/models/Description.java#L14

**Comment by manisha-shetty** [comment]
Hi. I ma trying to work on this but i see the master does not pass all tests. Any help?

**Comment by sshah-wework** [comment]
Hi @manisha-shetty! thanks for your help -- which tests are failing for you?

**Comment by wslulciuc** [comment]
Hey @manisha-shetty! We're happy to help. Looks like tests are passing in CI (see: https://circleci.com/gh/MarquezProject/marquez/1837).

We have a guide that outlines how to contribute [CONTRIBUTING.md](https://github.com/MarquezProject/marquez/blob/master/CONTRIBUTING.md). Let us know if you need any help with that.

**Comment by wslulciuc** [comment]
Hey, @manisha-shetty. Where you able to get test passing locally?

**Comment by wslulciuc** [comment]
@manisha-shetty was this an issue you still wanted to help out with?
