### ISSUE TITLE
Add test to ensure underscore support in Dataset URNs

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#312]
Let's add a test to [`DatasetUrnTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/common/models/DatasetUrnTest.java) to ensure underscores are supported.

**Example**

```
urn:foo:bar_baz
```

**Comment by ravikamaraj** [comment]
hi @wslulciuc, with code refactoring going in after this issue was created, underscore test case would now be more appropriate to UrnPatternTest class. Can you review, and let me know your thoughts
thanks

**Comment by wslulciuc** [comment]
Fixed #627
