### ISSUE TITLE
Add DatasetDao tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#314]
Our test coverage for [`DatasetDao`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/DatasetDao.java) is currently `< 25%`, let's add some tests to get it closer to `75%`

codecov link: https://codecov.io/gh/MarquezProject/marquez/src/master/src/main/java/marquez/db/DatasetDao.java

**Comment by hjpatel16** [comment]
Hey, I would like to work on it

**Comment by wslulciuc** [comment]
Hey @hjpatel16. Great to hear you'd like to help out! I'm actually fixing this issue in PR #395 (sorry, should've assigned this to myself sooner). Once merged into `master`, it will serve as an example on how to write tests for our DAO classes.

Is there an issue tagged with ["good first issue"](https://github.com/MarquezProject/marquez/labels/good%20first%20issue) you'd like to pick up?

**Comment by hjpatel16** [comment]
Actually, I was looking more than "good first issue" where I would be able to code more and contribute more. Let me know if you know any specific issue which will be perfect for me

**Comment by wslulciuc** [comment]
@hjpatel16, sure! How does adding a factory method to our response models sound? Full details can be found here #309. I know the issues related to the epic are labeled as "good first issue", but these changes are non-trivial and would require writing tests, with new methods used right away in our [resource](https://github.com/MarquezProject/marquez/tree/master/src/main/java/marquez/api/resources) classes.

Let me know if that's something you're interested in.

NOTE: You would need a separate PR per issue in the epic

**Comment by hjpatel16** [comment]
Yes, I would like to work on that epic. Thanks @wslulciuc, much appreciated

**Comment by wslulciuc** [comment]
Fixed #395
