### ISSUE TITLE
Add DatasetRowMapper tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#315]
Our test coverage for [`DatasetRowMapper`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/mappers/DatasetRowMapper.java) is currently `< 25%`, let's add some tests to get it closer to `75%`

codecov link: https://codecov.io/gh/MarquezProject/marquez/src/master/src/main/java/marquez/service/mappers/DatasetRowMapper.java

**NOTES:** For a great example test, see [`DatasetMapperTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/service/mappers/DatasetMapperTest.java)

**Comment by Violet-XiaoWeiHuang** [comment]
Hello @wslulciuc 
I'd like to work on this test. The reference link was broken. Is https://github.com/MarquezProject/marquez/pull/323  the same source?

**Comment by wslulciuc** [comment]
@Violet-XiaoWeiHuang, I updated the example mapper test in the issue. Yes, #323 the same source. Thanks for helping to increase our coverage!

**Comment by Violet-XiaoWeiHuang** [comment]
@wslulciuc 
I am struggling how to write this unit test. 
From my understanding to [DatasetRowMapper.java](https://github.com/MarquezProject/marquez/blob/ad9ab09b61f6f4c1ac55f99a6ea6b070cb9c1ef5/src/main/java/marquez/service/mappers/DatasetRowMapper.java), its 3 members needs to be tested. https://github.com/MarquezProject/marquez/blob/ad9ab09b61f6f4c1ac55f99a6ea6b070cb9c1ef5/src/main/java/marquez/service/mappers/DatasetRowMapper.java#L21-L23

Could you provide an example to me? Even with refer [DataSourceRowMapperTest.java](https://github.com/MarquezProject/marquez/blob/ad9ab09b61f6f4c1ac55f99a6ea6b070cb9c1ef5/src/test/java/marquez/service/mappers/DataSourceRowMapperTest.java), it's difficult for me to start. 

Thank you.

**Comment by Violet-XiaoWeiHuang** [comment]
Or could you provide a scenario to me about how to use DatasetRowMapper.java? 
@wslulciuc

**Comment by wslulciuc** [comment]
Fixed #627
