### ISSUE TITLE
Add DatasetRowMapper tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#316]
Our test coverage for [`DatasetRowMapper`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/mappers/DatasetRowMapper.java) is currently `< 25%`, let's add some tests to get it closer to `75%`

codecov link: https://codecov.io/gh/MarquezProject/marquez/src/master/src/main/java/marquez/db/mappers/DatasetRowMapper.java

**NOTE:** For a great example test, see [`DatasetRowExtendedMapperTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/db/mappers/DatasetRowExtendedMapperTest.java)

**Comment by ravikamaraj** [comment]
Hi @wslulciuc
I can pick this task, can you assign it to me. thanks

**Comment by wslulciuc** [comment]
@ravikamaraj Great! Thanks for the help. Note, I updated the example test in the description. Please use the following tests as a reference: https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/db/mappers/DatasetRowExtendedMapperTest.java

**Comment by wslulciuc** [comment]
Fixed: #532
