### ISSUE TITLE
Add DbTableInfoRowMapper tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#318]
Our test coverage for [`DbTableInfoRowMapper`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/mappers/DbTableInfoRowMapper.java) is currently `< 25%`, let's add some tests to get it closer to `75%`

codecov link: https://codecov.io/gh/MarquezProject/marquez/src/master/src/main/java/marquez/db/mappers/DbTableInfoRowMapper.java

**NOTE:** For a great example test, see [`DatasourceRowMapperTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/db/mappers/DatasourceRowMapperTest.java)

**Comment by hjpatel16** [comment]
Can I work on this issue?

**Comment by wslulciuc** [comment]
Thanks for working on this, @hjpatel16!

Fixed #413
