### ISSUE TITLE
Add  DbTableVersionRowMapper tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#319]
Our test coverage for [`DbTableVersionRowMapper`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/mappers/DbTableVersionRowMapper.java) is currently `< 25%`, let's add some tests to get it closer to `75%`

codecov link: https://codecov.io/gh/MarquezProject/marquez/src/master/src/main/java/marquez/db/mappers/DbTableVersionRowMapper.java

**NOTES:** For a great example test, see [`DataSourceRowMapperTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/db/mappers/DataSourceRowMapperTest.java)

**Comment by hjpatel16** [comment]
Hey @wslulciuc Can I work on this issue?

**Comment by wslulciuc** [comment]
@hjpatel16: You sure can. Thanks! (Sorry, a bit delayed in my responses)

**Comment by wslulciuc** [comment]
Fixed #442
