### ISSUE TITLE
Add  DbTableInfoRowMapper tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#320]
Our test coverage for [`DbTableInfoRowMapper`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/mappers/DbTableInfoRowMapper.java) is currently `< 25%`, let's add some tests to get it closer to `75%`

codecov link: https://codecov.io/gh/MarquezProject/marquez/src/master/src/main/java/marquez/service/mappers/DbTableInfoRowMapper.java

**NOTES:** For a great example test, see [`DataSourceRowMapperTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/service/mappers/DataSourceRowMapperTest.java)

**Comment by hjpatel16** [comment]
@wslulciuc  Can I work on this issue? I already added the test, if no one is working on it then I can submit the PR. Let me know asap. Thanks :)

**Comment by wslulciuc** [comment]
You sure can! Thanks,@hjpatel16

**Comment by hjpatel16** [comment]
I've submitted the PR. Please have a look. Thanks!

**Comment by wslulciuc** [comment]
Fixed #413
