### ISSUE TITLE
Return JobRunRow on JobRunRowMapper.map()

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#332]
Return [`JobRunRow`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/models/JobRunRow.java) on **JobRunRowMapper.map()** instead of [`JobRun`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/models/JobRun.java)

**Comment by Violet-XiaoWeiHuang** [comment]
@wslulciuc 
I'm interested in this project. 
Currently https://github.com/MarquezProject/marquez/blob/434b2ba30803bff6ce89b84a26e2754190ccb3f3/src/main/java/marquez/db/mappers/JobRunRowMapper.java#L30

on JobRunRowMapper.map(), it returns `JobRun`. Do you want to change to JobRunRow ?

**Comment by wslulciuc** [comment]
> Do you want to change to JobRunRow?

Yes, we want to decouple our service models from our DAO layer. Meaning, **JobRunRowMapper.map()** should map a (_raw_) DB row in our postgres instance, to a model we have defined representing an individual rows (=`JobRunRow`)

Thanks, @Violet-XiaoWeiHuang for working on this and please reach out with any questions! You can also reach out to use directly on gitter :) https://gitter.im/marquez-project/community

**Comment by Violet-XiaoWeiHuang** [comment]
#390

**Comment by wslulciuc** [comment]
Labeled issue with `needs info`, see discussion here: https://github.com/MarquezProject/marquez/pull/390#issuecomment-475404830

**Comment by wslulciuc** [comment]
Fixed #627
