### ISSUE TITLE
Remove AppWithPostgresRule

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#347]
[`AppWithPostgresRule`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/db/fixtures/AppWithPostgresRule.java) depends on `PreparedDbProvider` and `FlywayPreparer` which no longer are packaged with `jdbi3-testing` after `3.4.0`. This means we either pull in [`otj-pg-embedded`](https://github.com/opentable/otj-pg-embedded) as a dependency or look into a different approach. 

Until then, we can't bump `jdbi3-testing` and are pinned to version `3.3.0`

**Comment by ashulmanWeWork** [comment]
Do we have any insight as to why they are not longer bundled?
If there are no known disadvantages to PreparedDbProvider and FlywayPreparer, I don't mind adding them in separately as dependencies.

**Comment by wslulciuc** [comment]
Fixed #627
