### ISSUE TITLE
Normalize the use of '..DataSet..' to '..Dataset..'

### ISSUE THREAD

**Issue by roaraya8** [MarquezProject/marquez#350]
In the code there are many variables referencing 'datasets' which are being written in both forms:
- ...DataSet...'
- '...Dataset..'

For cleanliness and consistency let's opt for one of them like '..Dataset..'

**Comment by ashulmanWeWork** [comment]
For context, we decided on using Datasource.

**Comment by wslulciuc** [comment]
@ashulmanWeWork : Mind creating an issue to normalize `DataSource` to `Datasource`?

**Comment by ashulmanWeWork** [comment]
Sure - filed https://github.com/MarquezProject/marquez/issues/360.
