### ISSUE TITLE
Remove 'Create*' prefix from request payloads 

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#353]
We have a couple of classes still prefixed with `Create*`, so let's rename them to be consistent with our naming convention for request/response models.

- [CreateJobRunRequest](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/models/CreateJobRunRequest.java) **=>** `JobRunRequest`
- [CreateNamespaceRequest](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/models/CreateNamespaceRequest.java) **=>** `NamespaceRequest `

**Comment by OlenaVyshnevska** [comment]
Hi, can I work on this?

**Comment by wslulciuc** [comment]
You sure can, @OlenaVyshnevska! Thanks for the help.

**Comment by wslulciuc** [comment]
Fixed in PR #359
