### ISSUE TITLE
Rename class Job

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#358]
Let's rename **class** [Job](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/models/Job.java) to be consistent with our naming convention for request/response models:

* [Job](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/api/models/Job.java) **=>** `JobResponse`

**Comment by Violet-XiaoWeiHuang** [comment]
Hello @wslulciuc ,
I'd like to do this project, and I'm new to it too. 
You mention you want to rename model from `Job` => `JobResponse`, do you mean to rename including 
Job model declaration
https://github.com/MarquezProject/marquez/blob/7c6431bf6a82145f52cd679eb773468a01a9ef59/src/main/java/marquez/api/models/Job.java#L27

as well as the Job model being used, like 
https://github.com/MarquezProject/marquez/blob/7c6431bf6a82145f52cd679eb773468a01a9ef59/src/test/java/marquez/api/JobResourceTest.java#L38
https://github.com/MarquezProject/marquez/blob/434b2ba30803bff6ce89b84a26e2754190ccb3f3/src/test/java/marquez/api/JobTest.java#L24

**Comment by wslulciuc** [comment]
> You mention you want to rename model from `Job` => `JobResponse`, do you mean to rename including Job model declaration

Hey, @Violet-XiaoWeiHuang! Yeah, exactly. This issue renames the API model returned to callers when interfacing with our **Jobs API**. 

I'd recommended breaking up the change as follows:

1. Rename `Job` => `JobResponse`
2. Update all imports from **`marquez.api.models.Job`** to **`marquez.api.models.JobResponse`**
3. Address any compilation errors
4. Submit a PR :)

**Comment by wslulciuc** [comment]
Fixed #381
