### ISSUE TITLE
Normalize the use of DataSource to Datasource

### ISSUE THREAD

**Issue by ashulmanWeWork** [MarquezProject/marquez#360]
In the code there are many variables referencing 'datasets' which are being written in both forms:

* ...DataSource...'
* '...Datasource..'

For cleanliness and consistency let's opt for  '..Datasource..'.

**Comment by pbrahmbhatt3** [comment]
can i work on it?

**Comment by ashulmanWeWork** [comment]
Hi @pbrahmbhatt3, thanks for offering to take this on! I am currently working on the patch that will deliver Datasource functionality, and it will subsume large parts of this. For that reason, I recommend holding off on this.

**Comment by ashulmanWeWork** [comment]
Resolved in commit of datasource patch.
