### ISSUE TITLE
Bind {job} to JobName

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#375]
Let's update all [resources](https://github.com/MarquezProject/marquez/tree/master/src/main/java/marquez/api/resources) to bind the path variable `{job}` to the type [`JobName`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/common/models/JobName.java)

**Comment by pbrahmbhatt3** [comment]
can i work on it?

**Comment by wslulciuc** [comment]
Sure! Thanks for the help, @pbrahmbhatt3!

**Comment by pbrahmbhatt3** [comment]
Can you give me some suggestions on where to start from?

**Comment by wslulciuc** [comment]
Sure! This issue is part of an epic: _Bind @PathParam to custom types_ #376. I recommend looking over the epic if you haven't already. It outlines an example of how to bind a namespace present in a path (=endpoint) to the type [`NamespaceName`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/common/models/NamespaceName.java). A similar approach would be taken for [`JobName`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/common/models/JobName.java).

Does that help, @pbrahmbhatt3?

**Comment by pbrahmbhatt3** [comment]
Yes it does. Thanks. :D

**Comment by wslulciuc** [comment]
Fixed #385
