### ISSUE TITLE
Pull list of allowed datasource types from configuration

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#401]
The list of allowed datasource types is something which will change over time and will be very different across organizations. At first these will likely be defined statically within code, but moving this out into configuration would make Marquez Core more extensible.

**Comment by roaraya8** [comment]
would make sense to add this extension as _plugins_ or _connectors_ ? In case some of those sources might have a very specific set of attributes.

**Comment by wslulciuc** [comment]
Discussion moved to #698

**Comment by julienledem** [comment]
Datasource type is now a string.
