### ISSUE TITLE
Listing datasets is broken

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#423]
```
$ ./datasets.py --list --namespace=demo
http://localhost:5000/api/v1/namespaces/demo/datasets/
{"code":500,"message":"There was an error processing your request. It has been logged (ID c7692f4fc7d58686)."}
```

The issue seems to be in the DAO layer:

```
java.lang.UnsupportedOperationException: No argument factory registered for 'Namespace(value=demo)' of type class marquez.common.models.Namespace
```

**Comment by wslulciuc** [comment]
I think you might be behind with `master`? The class `marquez.common.models.Namespace` was replaced with [`NamespaceName`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/common/models/NamespaceName.java).

**Comment by sshah-wework** [comment]
You're right, I was building off a pretty old commit. Pulled and it's good now.
