### ISSUE TITLE
Datasource Resource throws a 500 on invalid URN input

### ISSUE THREAD

**Issue by ashulmanWeWork** [MarquezProject/marquez#458]
Expected behavior is to throw a 400 (bad request).

The reason a 400 is not generated is because the URN is not part of the initial request. It's generated at the service layer, and by that point, any exceptions there come up as service exceptions -> 500.

One solution would be to potentially construct the URN at the resource layer to test whether it can be done and throw a 400 if the URN creation throws an `IllegalArgumentException`.

The other option is to catch it in the service layer and pass up a BadRequestException (or similar).

**Comment by wslulciuc** [comment]
Fixed #627
