### ISSUE TITLE
Java 10/11 support

### ISSUE THREAD

**Issue by acruise** [MarquezProject/marquez#474]
Lots of exceptions are thrown when trying to start the shadowJar `server` on Java 10.  I realize the homepage specifies Java 8, but it'd be good to modernize a little ;)

**Comment by wslulciuc** [comment]
Agreed! Would you be interesting helping out and seeing what would be involved to support `Java10`?

**Comment by acruise** [comment]
Perhaps, let's see if I can figure out how to get it working first (*shakes fist at nodejs*) ;)

**Comment by powersam** [comment]
[root@instance-20200713-1004 marquez-main]# java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)


[root@instance-20200713-1004 marquez-main]# gradle shadowJar 

> Configure project :
Running [git, branch, --no-color] produced an error: [fatal: Not a git repository (or any parent up to mount point /u01)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).]

FAILURE: Build failed with an exception.

* Where:
Build file '/u01/marquez/marquez-main/build.gradle' line: 109

* What went wrong:
A problem occurred evaluating root project 'marquez'.
> java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 769ms

**Comment by wslulciuc** [comment]
@powersam I'm also on java8:

```
$ java -verison
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

I recommend using the script [`gradlew`](https://github.com/MarquezProject/marquez/blob/main/gradlew) checked in along with the project. From the base of the project repo, run:

```
$ ./gradlew shadowJar

BUILD SUCCESSFUL in 674ms
3 actionable tasks: 3 up-to-date
```

Let me know this helps!

**Comment by wslulciuc** [comment]
We're now on `Java11`. Is this still an issue @acruise @powersam ?
