### ISSUE TITLE
JdbiRule.embeddedPostgres().migrateWithFlyway() deprecated

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#490]
Jdbi has deprecated [`migrateWithFlyway()`](http://jdbi.org/apidocs/org/jdbi/v3/testing/JdbiRule.html#migrateWithFlyway--). We should use [`withMigration(Migration)`](http://jdbi.org/apidocs/org/jdbi/v3/testing/JdbiRule.html#withMigration-org.jdbi.v3.testing.Migration-) instead.

**Comment by ravikamaraj** [comment]
Hi @wslulciuc 
I can pick this task, can you assign it to me. thanks

**Comment by wslulciuc** [comment]
@ravikamaraj sure and thanks!

**Comment by wslulciuc** [comment]
Fixed: #531
