### ISSUE TITLE
Update test classes on Mock usage

### ISSUE THREAD

**Issue by ravikamaraj** [MarquezProject/marquez#533]
Update all test classes which uses Mock objects, to follow below Mock usage

```
@Mock private StatementContext context;
  @Before
  public void setup() {
    MockitoAnnotations.initMocks(this);
  }
```

**Reference:**
[DatasetRowMapperTest.java](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/db/mappers/DatasetRowMapperTest.java)

**Comment by wslulciuc** [comment]
@ravikamaraj: We can even go a step further and remove the `setup()` using [MockitoRule](https://static.javadoc.io/org.mockito/mockito-core/2.27.0/org/mockito/junit/MockitoRule.html). For example:

```java
 public class ExampleTest {

     //Creating new rule with recommended Strictness setting
     @Rule public MockitoRule rule = MockitoJUnit.rule().strictness(Strictness.STRICT_STUBS);

     @Mock
     private List list;

     @Test
     public void shouldDoSomething() {
         list.add(100);
     }
 }
```

> Initializes mocks annotated with Mock, so that explicit usage of MockitoAnnotations.initMocks(Object) is not necessary. Mocks are initialized before each test method.

**Comment by ravikamaraj** [comment]
looks pretty, yes good option to use

**Comment by ravikamaraj** [comment]
I would pick this task today

**Comment by ravikamaraj** [comment]
update: work in progress, should be able to wrap in couple of days

**Comment by wslulciuc** [comment]
@ravikamaraj, awesome! Thanks again for helping out with this issue.

**Comment by ravikamaraj** [comment]
https://github.com/MarquezProject/marquez/pull/538
