### ISSUE TITLE
Create JobRow db model

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#535]
The more "modern" DAOs (like Dataset) return a proper db model instead of a service model. JobDao was earlier DAO which did not do this. 

- Create a `JobRow` class within `marquez.db.models`
- Return `JobRow` types from `JobDao` methods which fetch data
- Accept `JobRow` arguments from `JobDao` methods which do `INSERT`s
- Create a `JobMapper` with a `marquez.db.models.JobRow` -> `marquez.service.models.Job` `map` function
- Add a `JobRow` generator to `marquez.db.models.DbModelGenerator`

**Comment by wslulciuc** [comment]
Fixed #627
