### ISSUE TITLE
Create JobVersion row db model

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#536]
The more "modern" DAOs (like `Dataset`) return a proper db model instead of a service model. `JobVersionDao` was earlier DAO which did not do this.

Create a `JobVersionRow` class within `marquez.db.models`
Return `JobVersionRow` types from `JobVersionDao` methods which fetch data
Accept `JobVersionRow` arguments from JobDao methods which do INSERTs
Create a `JobVersionMapper` with a `marquez.db.models.JobVersionRow` -> `marquez.service.models.JobVersion` map function
Add a `JobVersionRow` generator to `marquez.db.models.DbModelGenerator`

**Comment by wslulciuc** [comment]
Fixed #627
