### ISSUE TITLE
Add JobRowMapper tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#555]
Our test coverage for [`JobRowMapper`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/mappers/JobRowMapper.java) is currently `< 25%`, let's add some tests to get it closer to `75%`

codecov link: https://codecov.io/gh/MarquezProject/marquez/src/master/src/main/java/marquez/db/mappers/JobRowMapper.java

**NOTES:** For a great example test, see [`DatasetRowExtendedMapperTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/db/mappers/DatasetRowExtendedMapperTest.java)

**Comment by wslulciuc** [comment]
@ronthalanki-wework assigning this to you. Thanks for the help!

**Comment by ronthalanki-wework** [comment]
closed by #561
