### ISSUE TITLE
Docker Failed to Build

### ISSUE THREAD

**Issue by danielheth** [MarquezProject/marquez#574]
Windows 10; Docker 18.09.2.6247962
```
$ docker-compose up
Building app
Step 1/20 : FROM openjdk:8-jdk AS base
 ---> b84359d0cbce
Step 2/20 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 42039e9515a1
Step 3/20 : COPY gradle gradle
 ---> Using cache
 ---> 76174613b1e7
Step 4/20 : COPY gradle.properties gradle.properties
 ---> Using cache
 ---> b49a09c65f13
Step 5/20 : COPY gradlew gradlew
 ---> Using cache
 ---> 72a86bf7d567
Step 6/20 : COPY settings.gradle settings.gradle
 ---> Using cache
 ---> 63497d64a7f4
Step 7/20 : RUN ./gradlew --version
 ---> Running in 1e77c441fd78
/usr/bin/env: ‘sh\r’: No such file or directory
ERROR: Service 'app' failed to build: The command '/bin/sh -c ./gradlew --version' returned a non-zero code: 127
```

**Comment by danielheth** [comment]
needed to install Gradle (https://gradle.org/install/  not mentioned in documentation) as well as run the `gradle wrapper` command in order to get `gradlew` command available.

**Comment by wslulciuc** [comment]
Hey, @danielheth! After installing [Docker Desktop for Windows](https://docs.docker.com/docker-for-windows/install/), you should be able to run the following cmd from the base of the repo:

```bash
$ docker-compose up --build
```

Looks like that wasn't the case?

Regarding Gradle setup, everything needed to get up and running with Marquez is checked in (including the wrapper):

-  [`gradle/wrapper`](https://github.com/MarquezProject/marquez/tree/master/gradle/wrapper)
- [`gradlew`](https://github.com/MarquezProject/marquez/blob/master/gradlew)
- etc.

The [`README.md`](https://github.com/MarquezProject/marquez/blob/master/README.md) does have a [requirements](https://github.com/MarquezProject/marquez#requirements ) section, but we're always looking to improve our docs. Are there any recommendations you have to help others getting started?

**Comment by wslulciuc** [comment]
@danielheth, closing this issue, but please let us know how we can help if you are stilling seeing the error.
