### ISSUE TITLE
Remove usage of Generator

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#577]
The **class** [`Generator`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/service/models/Generator.java) has been _deprecated_ in favor of package specific generators:

- [`ApiModelGenerator`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/api/models/ApiModelGenerator.java)
- [`ServiceModelGenerator`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/service/models/c.java)
- [`DbModelGenerator`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/db/models/DbModelGenerator.java)
- [`CommonModelGenerator`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/common/models/CommonModelGenerator.java)

Let's replace the usage of  **class** [`Generator`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/service/models/Generator.java) in our tests with the respective generators listed above.

**Comment by wslulciuc** [comment]
@alulc: Assigning this to you. Thanks!

**Comment by wslulciuc** [comment]
@alulc: Where you able to look into this issue?

**Comment by ravikamaraj** [comment]
@alulc / @wslulciuc , I can pick this task, if you are ok with it. thanks

**Comment by wslulciuc** [comment]
That'd be great! But, let's give @alulc a few days to get back before picking up the issue. It's possible he may have already started working on it.

**Comment by ravikamaraj** [comment]
sure

**Comment by alulc** [comment]
@ravikamaraj sure, you can take it. thanks!

**Comment by ravikamaraj** [comment]
thanks @alulc
