### ISSUE TITLE
Add docker compose

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#58]
To simplify getting started / up and running with marquez, we'll want to add support for `docker-compose`

**Note:** depends on #44

**Comment by wslulciuc** [comment]
@harels : Merged #44, which unblocks you on this issue. Thanks again for picking this up!

**Comment by chordol** [comment]
Running `docker-compose up` does not make port 8081 available, per README.md:  
"Then browse to the admin interface: http://localhost:8081"

`docker ps` produces:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                              NAMES
e933a8389577        marquez_app         "/usr/src/app/entryp…"   About a minute ago   Up About a minute   0.0.0.0:5000-5001->5000-5001/tcp   marquez_app_1
086651fecc03        postgres:9.6        "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:5432->5432/tcp             marquez_db_1
```

This prohibits easy evaluating the project by just running docker-compose command.

**Comment by wslulciuc** [comment]
@chordol: Thanks for evaluating the project and pointing out a discrepancy in our docs! We are working on a _Quickstart_ guide (#477) that will provide comprehensive steps to get started with Marquez, but have addressed the doc discrepancy you pointed out in #480.

**Comment by wslulciuc** [comment]
> http://localhost:5000/ responds with:
{"code":404,"message":"HTTP 404 Not Found"}

The current version of the API (**v1**) is part of the URL, so certain endpoints will contain the prefix `/api/<version>/`. For example, calling `/namespaces/{namespace}` requires you prefix the URL with `/api/v1`, so to access the API call `/api/v1/namespaces/{namespace}`.

**Comment by chordol** [comment]
Thanks for the response @wslulciuc!
