### ISSUE TITLE
Add namespace request/response tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#584]
For great examples see:

- [`DatasetRequestTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/api/models/DatasetRequestTest.java)
- [`DatasetResponseTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/api/models/DatasetResponseTest.java)
- [`DatasetsResponseTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/api/models/DatasetsResponseTest.java)

**Comment by ravikamaraj** [comment]
@wslulciuc , I can pick this task

**Comment by ravikamaraj** [comment]
The task is complete, can you close this ticket. thanks

**Comment by wslulciuc** [comment]
@ravikamaraj, mind linking issues in future PRs as outlined in our [`CONTRIBUTING.md`](https://github.com/MarquezProject/marquez/blob/master/CONTRIBUTING.md)?

**Comment by wslulciuc** [comment]
Fixed #593

**Comment by ravikamaraj** [comment]
> @ravikamaraj, mind linking issues in future PRs as outlined in our [`CONTRIBUTING.md`](https://github.com/MarquezProject/marquez/blob/master/CONTRIBUTING.md)?

sure
