### ISSUE TITLE
Add datasource request/response tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#585]
For great examples see:

- [`DatasetRequestTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/api/models/DatasetRequestTest.java)
- [`DatasetResponseTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/api/models/DatasetResponseTest.java)
- [`DatasetsResponseTest`](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/api/models/DatasetsResponseTest.java)

**Comment by ravikamaraj** [comment]
@wslulciuc , I can pick this task
