### ISSUE TITLE
gradle `db clean` should delete test db file

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#62]

**Comment by sshah-wework** [comment]
At the moment, doing a db clean / migrate does not clean up the local test database, leading to the schema diverging from the dev environment.

**Comment by ashulmanWeWork** [comment]
Thanks for noting this issue. All for fixing it.

**Comment by wslulciuc** [comment]
@sshah-wework : Is this still an issue?

**Comment by wslulciuc** [comment]
@sshah-wework @ashulmanWeWork: It seems like this is no longer an issue? Closing for now, be let's 
reopen if this error is observed in the future.
