### ISSUE TITLE
Reorganize Dropwizard service

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#66]
The current organization of our Dropwizard has no clear home for business logic, leaving us to push too much logic down into the DAO or Resources (without any guiding principles on when or where). We should consider re-organizing the project. We should also use patterns to reinforce good hygiene like having separate Representation objects for both requests and responses, which can help avoid unexpected bugs.

The Dropwizard docs suggest separating the business logic into separate package from the reference objects and the resources. The Dropwizard docs also making passing mention of request / response entities, although it does not emphasize the importance of this for good service design. To that end, we probably want to introduce:

- Controllers for request / response handling
- Service classes
- Request / Response entities

Thoughts?

**Comment by sshah-wework** [comment]
We may also want a standardize the validation pattern across all endpoints.

**Comment by wslulciuc** [comment]
@sshah-wework In complete agreement. I converted this issue into an epic #100
