### ISSUE TITLE
Add source support for Filesystems as datasource type

### ISSUE THREAD

**Issue by nkijak** [MarquezProject/marquez#694]
The current list of source types is lacking a filesystem type, either disk based or distributed (S3, GCS, etc.).  The simple fix is an addition of those to the SourceType enum, but this might lead to an explosion of types.  Perhaps a better fix is a hierarchical set of types as described by @julienledem on [gitter](https://gitter.im/marquez-project/community?at=5e13aa82e409da486cd725ce)
> As we add more data sources I think we should revisit what is a generic source type and what is just an attribute of those generic source types.I think we could change the source types to be: DATABASE (includes Redshift, Vertica, ...), STREAM (Kafka, Kinesis, ...), FILESYSTEM (S3, GCS, ...), VERSIONED_TABLE_FORMAT (Iceberg, DeltaLake). Those top level are defined as an enum as they have different properties. Then "Redshift", "Kinesis", ... becomes a value in a field to provide more information to the user. The service doesn't do anything special with it besides validating it against a list in a configuration file.

**Comment by frankcash** [comment]
Is this WIP?

**Comment by wslulciuc** [comment]
@frankcash Yep! I've finally been able to get back to working on this feature. You can follow the progress here https://github.com/MarquezProject/marquez/issues/708

**Comment by julienledem** [comment]
We have now loosened the constraint and the datasource type is a string.
