### ISSUE TITLE
Add column qualifier to table sources

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#705]
Let's add the column `qualifier` to **table** `sources`:

| COLUMN         | TYPE      |
|----------------|-----------|
| uuid           | `UUID`    |
| type           | `ENUM`    |
| qualifier       | `ENUM`    |
| created_at     | `DATE`    |
| updated_at     | `DATE`    |
| name           | `VARCHAR` |
| connection_url | `VARCHAR` |
| description    | `TEXT`    |

**Comment by julienledem** [comment]
This is deprecated
