### ISSUE TITLE
stop when it run reaches 75%

### ISSUE THREAD

**Issue by liuzrong** [MarquezProject/marquez#736]
when I run "./gradlew.bat run --args 'server config.yml'"  stop at 75%,what I should do?
following is log:
INFO  [2020-04-02 10:25:52,878] org.eclipse.jetty.server.Server: Started @15295ms
DEBUG [2020-04-02 10:25:52,878] org.eclipse.jetty.util.component.AbstractLifeCycle: STARTED @15295ms Server@49a26d19{STARTED}[9.4.26.v20200117]
DEBUG [2020-04-02 10:25:52,878] org.eclipse.jetty.util.thread.QueuedThreadPool: run acceptor-0@1f2f0109 in InstrumentedQueuedThreadPool[dw-admin]@6b0615ae{STARTED,1<=5<=64,i=0,r=6,q=0}[ReservedThreadExecutor@ad9e63e{s=0/6,p=0}]
<=========----> 75% EXECUTING [1h 18m 44s]

**Comment by wslulciuc** [comment]
@liuzrong Sure, happy to help! Did you create your `config.yml` with the steps outlined [here](https://github.com/MarquezProject/marquez#step-2-create-configyml)?

**Comment by liuzrong** [comment]
Yes, I created and configured my postgresql.

**Comment by liuzrong** [comment]
Yes, I created, and configured my postgresql发自我的华为手机-------- 原始邮件 --------发件人： Willy Lulciuc <notifications@github.com>日期： 2020年4月2日周四 13:39收件人： MarquezProject/marquez <marquez@noreply.github.com>抄送： liuzrong <18753365319@163.com>, Mention <mention@noreply.github.com>主    题： Re: [MarquezProject/marquez] stop when it run reaches 75% (#736)
@liuzrong Sure, happy to help! Did you create your config.yml with the steps outlined here?

**Comment by wslulciuc** [comment]
Locally dev environments can be hard to properly diagnose. If you are ok with using demo data, and only want to explore the functionality of Marquez, you have two solid options:

1.  **Marquez**: To start the API server only, you can checkout our [Quickstart](https://marquezproject.github.io/marquez/quickstart.html)
2. **Marquez + UI**" To start the API server and [UI](https://github.com/MarquezProject/marquez-web), you can follow [Running with Docker](https://github.com/MarquezProject/marquez-web#running-with-docker)

Let me know if this helps getting started. We can debug further if you'd like to run directly from source using the `jar` with your own postgres instance (outside of docker).

**Comment by wslulciuc** [comment]
@liuzrong Are you still seeing this issue?

**Comment by wslulciuc** [comment]
@liuzrong Closing this issue for now, but please let us know if you running still into this issue.
