### ISSUE TITLE
docker build is not working with master branch

### ISSUE THREAD

**Issue by krishna-meduri-twi** [MarquezProject/marquez#737]
Docker build is failing with, 

> db_1   | 2020-04-07 11:46:43.557 UTC [82] ERROR:  relation "namespaces" does not exist at character 56

While going through the remaining part of the log I have found these,

> app_1  | WARN  [2020-04-07 11:46:42,333] org.flywaydb.core.internal.scanner.classpath.ClassPathScanner: **Unable to resolve location classpath:db/migration**. Note this warning will become an error in Flyway 7.
app_1  | INFO  [2020-04-07 11:46:42,646] org.flywaydb.core.internal.database.DatabaseFactory: Database: jdbc:postgresql://db:5432/marquez (PostgreSQL 12.1)
app_1  | INFO  [2020-04-07 11:46:42,699] org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory: Creating Schema History table "public"."flyway_schema_history" ...
app_1  | INFO  [2020-04-07 11:46:42,778] org.flywaydb.core.internal.command.DbMigrate: Current version of schema "public": << Empty Schema >>
app_1  | INFO  [2020-04-07 11:46:42,780] org.flywaydb.core.internal.command.DbMigrate: Schema "public" is up to date. No migration necessary.
app_1  | INFO  [2020-04-07 11:46:42,786] marquez.db.DbMigration: Successfully applied '0' migrations to database.

 Which made me realise that the path for migration scripts, **db/migration**, is being referenced in a wrong manner. Could someone please help me fix the issue, as it might become showstopper for those who are using docker environments?

As a workaround, tried moving **db/migration out of marquez folder** (under resource folder) and docker build worked fine.

Thank you.

**Comment by wslulciuc** [comment]
Hey, @krishna-meduri-twi! Thanks for opening this issue. We've recently updated the migration path in #731 allowing Marquez to be more extensible. But, we didn't provide an override of the migration path in `config.example.yml`. I've opened an issue and will get a fix out shortly!

**Comment by wslulciuc** [comment]
@krishna-meduri-twi We've merged a fix to update the migration path (see #738). Let us know if you're still seeing this issue!

**Comment by krishna-meduri-twi** [comment]
@wslulciuc Thank you very much for fixing the issue. Docker build is working with the master branch. Hence, closing this issue.
