### ISSUE TITLE
Add Version

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#740]
Let's add the **class** `Version` that wraps, validates, and replaces instances of `UUID` as versions. The class will also help reduce ambiguity. For example:

```java
// Dataset
final String datasetVersionString = "2bc7730b-3b75-49a8-9959-28ebe8d0ee41";
final Version datasetVersion = Version.of(datasetVersionString);

// Job
final String jobVersionString = "6a21b12e-46bc-433d-89a7-73add4d16111";
final Version jobVersion = Version.of(jobVersionString);
```

**Comment by ravikamaraj** [comment]
@wslulciuc , I can help you with this task. thanks

**Comment by wslulciuc** [comment]
Thanks, @ravikamaraj! Really appreciate the help. For this issues, I was think we can replace the `UUID` type with your `Version` implementation in the following classes:

- [`DatasetVersionId`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/models/DatasetVersionId.java)
- [`JobVersionId`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/models/JobVersionId.java)
