### ISSUE TITLE
Add RunId

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#741]
Let's add the **class** `RunId` that wraps, validates, and replaces `UUID` as a run ID. The class will also help reduce ambiguity. For example:

```java
final String idString = "b251eae0-b7d6-41c0-aee3-35db5ce0a039";
final RunId runId = RunId.of(idString);
```

see https://github.com/MarquezProject/marquez/blob/724d622feca5f987140dd51f8bd2f065c272a0e7/src/main/java/marquez/common/models/RunId.java

**Comment by ravikamaraj** [comment]
@wslulciuc , I can help you with this task. thanks

**Comment by wslulciuc** [comment]
Awesome. Thanks, @ravikamaraj!

**Comment by ravikamaraj** [comment]
update: I would begin working on this issue in couple of days

**Comment by wslulciuc** [comment]
Sounds great! Appreciate the update, @ravikamaraj
