### ISSUE TITLE
Add RunState

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#742]
Let's move [`Run.State`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/models/Run.java#L58) outside of the `Run` class to `common.models.RunState` for use across layers (_api_, _service_, _db_).

**Comment by ravikamaraj** [comment]
@wslulciuc , I can help you with this task. thanks

**Comment by wslulciuc** [comment]
Thanks, @ravikamaraj! Let us know if there's anything we can help out with.
