### ISSUE TITLE
Quick Start Issue - docker-compose.yaml

### ISSUE THREAD

**Issue by frankcash** [MarquezProject/marquez#745]
# Issue

`docker-compose.yaml` points to a config file that doesn't exist by default

## Proposed Solution
In the Quick Start docks there is no mention of making `config.yaml`, and it is currently defined to `/usr/src/app/config.yml`.  This is not defined in the `dockerfile` nor is there one provided via volume in docker-compose.  I think it would be best to use the `config.dev.yaml` that the `dockerfile` does pull in.  https://github.com/MarquezProject/marquez/blob/master/Dockerfile#L19

This would require a change to this line:
https://github.com/MarquezProject/marquez/blob/master/docker-compose.yml#L11 

And then an update to the host in the `config.dev.yaml` to point at the proper host for the db.

**Comment by frankcash** [comment]
I will happily create a PR to correct this 👍 just let me know if this change is desired

**Comment by wslulciuc** [comment]
> [config.yaml] is not defined in the dockerfile nor is there one provided via volume in docker-compose.

@frankcash Thanks for opening this issue! The `config.example.yml` is mounted  and renamed as `config.yml` (https://github.com/MarquezProject/marquez/blob/master/docker-compose.yml#L19). Did you run into any issues while following the steps in the quickstart?

Either way, I agree, using `config.dev.yml` would be best. Would really love to see a PR to use the dev config. Thanks!

**Comment by wslulciuc** [comment]
@frankcash I've updated `docker-compose.yml` to use `marquez.dev.yml`, see #792
