### ISSUE TITLE
Flaky job creation test

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#749]
Let's look into why the job creation integration test ( [`testApp_createJob `](https://github.com/MarquezProject/marquez/blob/master/src/test/java/marquez/MarquezAppIntegrationTest.java#L303))  is flaky, see CI run that shows the test _failing_, [4791](https://circleci.com/gh/MarquezProject/marquez/4791) then _passing_ after rerunning tests in CI [4797](https://circleci.com/gh/MarquezProject/marquez/4797)

**Comment by julienledem** [comment]
This is not a problem anymore
