### ISSUE TITLE
Use UUID regex in URI validation

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#75]
Instead of validating UUID separately, look into: https://www.mkyong.com/webservices/jax-rs/jax-rs-path-uri-matching-example/

**Comment by wslulciuc** [comment]
We will validate a run ID by binding `{id}` in `jobs/runs/{id}/*` to [RunId](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/common/models/RunId.java)
