### ISSUE TITLE
Proposal to rename the master branch

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#767]
As has been discussed on numerous open source projects recently. I’d propose to rename the ‘master’ branch to ‘main’ to avoid the unnecessary reference to slavery with the master/slave terminology. 

See here for reference on the origin of the « master branch » in git:
https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html

This should be an easy enough change and ‘main branch’ is pretty clear what it refers too.

**Comment by wslulciuc** [comment]
The `master` branch has been renamed to `main`. Thanks @julienledem for proposing the name change and supporting a welcoming community for the project.
