### ISSUE TITLE
Add other source types for Google Cloud

### ISSUE THREAD

**Issue by yu-iskw** [MarquezProject/marquez#768]
We would like to support other source types for Google Cloud.

- Google Cloud Storage
- BigQuery
- Spanner
- BigTable
- Firestore

**Comment by wslulciuc** [comment]
Hey, @yu-iskw! Yeah, very reasonable to also support GCP source types. I will add them when as I work on #708

**Comment by julienledem** [comment]
@yu-iskw Datasource type is now less constrained and will accept those values
