### ISSUE TITLE
POST to PUT as needed

### ISSUE THREAD

**Issue by sreev** [MarquezProject/marquez#788]
tag dataset
/namespaces/{namespace}/datasets/{dataset}/tags/{tag}

tag field
/namespaces/{namespace}/datasets/{dataset}/fields/{field}/tags/{tag}

both of these are POST method calls, now.
but with empty payload.
may change to PUT method calls to be consistent with the rest ?

**Comment by wslulciuc** [comment]
@sreev It's okay to have an empty payload on `POST`s. For the tag endpoints you, the caller is performing an action on a dataset resource: _tag a dataset_, _tag a field_. Really, tags are metadata on top of the metadata we have already collected for datasets. This approach is consistent across APIs. That is, we collected metadata for datasets and jobs with `PUT`, and any metadata we'd like to link, we use `POST`. How we collect [run transitions metadata](https://marquezproject.github.io/marquez/openapi.html#tag/Jobs/paths/~1jobs~1runs~1{id}~1start/post) is a great example on our thinking for the tags API.
