### ISSUE TITLE
Proposal: write only support for metadata

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#798]
As we integrate Marquez with frameworks / systems like `Airflow`, `Spark` and others, the need to have a "collect only" / "write only" mode exposed by our clients  ([Java](https://github.com/MarquezProject/marquez-java), [Python](https://github.com/MarquezProject/marquez-python))  becomes more and more apparent. A write only mode would simplify integrations efforts by not depending on the response of an API call (i.e. non-blocking). An added benefit is the ability to make the backend where metadata is sent configurable (more details on the `backend` concept below). As we begin to start the discussions around an _Open Lineage_ standard, a backend will help with metadata consumption by other systems (ex: `Kafka`), not just `Marquez`.

## Proposal

> **Note**: All examples are in `Java`, but the `Python` client will have a similar implementation.

Below, we define the methods for the **class** **`MarquezWriteOnlyClient`**:

```java
  public void createNamespace(String namespaceName, NamespaceMeta namespaceMeta) {}
  public void createSource(String sourceName, SourceMeta sourceMeta) {}
  public void createDataset(String namespaceName, String datasetName, DatasetMeta datasetMeta) {}
  public void createJob(String namespaceName, String jobName, JobMeta jobMeta) {}
  public void createRun(String namespaceName, String jobName, RunMeta runMeta) {}
  public void markRunAs(String runId, RunState runState, @Nullable Instant at) {}
  public void markRunAsRunning(String runId) {}
  public void markRunAsRunning(String runId, @Nullable Instant at) {}
  public void markRunAsCompleted(String runId) {}
  public void markRunAsCompleted(String runId, @Nullable Instant at) {}
  public void markRunAsAborted(String runId) {}
  public void markRunAsAborted(String runId, @Nullable Instant at) {}
  public void markRunAsFailed(String runId) {}
  public void markRunAsFailed(String runId, @Nullable Instant at) {}
```

The API mirrors the interface for  [`MarquezClient`](https://github.com/MarquezProject/marquez-java/blob/main/src/main/java/marquez/client/MarquezClient.java), but with all methods having `void` as the return type. To simplify how new instances of a client are created, the following factory class **`Clients`** will be defined:

```java
public final class Clients {
  public static MarquezClient newClient(@NonNull final URL baseUrl) {
    return MarquezClient.builder().baseUrl(baseUrl).build();
  }

  public static MarquezWriteOnlyClient newWriteOnlyClient(@NonNull final Backend backend) {
    return new MarquezWriteOnlyClient(backend);
  }
}
```

Here's an example on how to create a write only client:

```java
MarquezWriteOnlyClient writeOnlyClient = Clients.newWriteOnlyClient(Backend)
```

A write only client also depends on a _backend_. A `Backend` is configurable and lets the client know where to write dataset and job metadata. Initially, we will support the following backends:

* `HTTP` - Write metadata to Marquez
* `FILE` - Write metadata to a file. Each line in the file will have the format (as `json`):

   ```
   # Line format
   {
     "method": PUT|POST,
     "path": string,
     "headers": object,
     "payload": object
   }

   # Example line in file (spaces / newline added for readability)
   {
     "method": "PUT",
     "path": "/api/v1/namespaces/my-namespace",
     "headers": {
       "User-Agent": "marquez-python/0.6.0"
     },
     "payload":  {
       "ownerName": "me",
       "description": "my namespace for testing."
     }
   }
   ```

Below, we define the methods for the interface **`Backend`**:

```java
void put(String path, String json);
void post(String path);
void post(String path, @Nullable String json);
```

You can checkout the WIP implementation for java here: https://github.com/MarquezProject/marquez-java/tree/feature/write-only-client

## Related Issues

*  #795 

/cc @julienledem @sreev

**Comment by julienledem** [comment]
resolved by MarquezProject/marquez-java#89 MarquezProject/marquez-python#92
