### ISSUE TITLE
Explore using DatabasePreparer when creating a database for integration tests

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#81]
Do we need our own `PreparedDbRule`? We're dynamically generating the `config.yml`, which I'm not a fan of (and something I think we can hopefully avoid). Looking at the src for [PreparedDbRule](https://github.com/opentable/otj-pg-embedded/blob/master/src/main/java/com/opentable/db/postgres/junit/PreparedDbRule.java#L55), on instantiation, it's creating the DB connection based on the details contained in [DatabasePreparer](https://github.com/opentable/otj-pg-embedded/blob/master/src/main/java/com/opentable/db/postgres/embedded/DatabasePreparer.java#L30). Worth exploring that as an option.

**Comment by ashulmanWeWork** [comment]
Checked in a fix that gets us a cleaner solution (thanks @wslulciuc for the pointers). There is some more work we can do to make it even cleaner, but this will hopefully resolve the issue of intermittent test failures.

**Comment by wslulciuc** [comment]
Let's use [JdbiRule](http://jdbi.org/apidocs/org/jdbi/v3/testing/JdbiRule.html) instead to manage a Jdbi instance pointing to a managed database.
