### ISSUE TITLE
Proposal: Add auth support to clients

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#817]
With the official `jar` for Marquez now [published](https://search.maven.org/search?q=a:marquez), it allows users of the API to both build and extend existing functionality. This also means some level of support for authentication is needed for our clients ([Java](https://github.com/MarquezProject/marquez-java), [Python](https://github.com/MarquezProject/marquez-python)). Let's add initial support for an API key to authenticate requests. That is, we will add initial support for authentication via _bearer auth_:

```
"Authorization: Bearer [API-KEY]"
```

The `Authorization` header will be added to each request via the client. We outline how to configure a client with an API key below.

### Java

```java
MarquezClient client = MarquezClient().builder()
  .baseUrl("http://localhost:5000")
  .apiKey("[API-KEY]")
  .build()
```

### Python

```python
client = MarquezClient(url='http;//localhost:5000', api_key='[API-KEY]')
```

> **Note:** Marquez will remain, by default, to not require any form of authentication or authorization. This proposal is only for cases where users have decided to import the `marquez.jar` as a dependency into their app and extend the APIs with some form of authentication (i.e. API keys). 

/cc @julienledem @phixMe @sreev

**Comment by wslulciuc** [comment]
API key support has been introduced in `marquez-java`[0.4.3](https://github.com/MarquezProject/marquez-java/releases/tag/0.4.3), and `marquez-python` [0.7.10](https://github.com/MarquezProject/marquez-python/releases/tag/0.7.10) 🎉

**Comment by Leonlifc23** [comment]
@wslulciuc 
before the client call api ，how does server config the auth? in db or any config file?
