### ISSUE TITLE
Why the app failed to connect to database

### ISSUE THREAD

**Issue by HondaHsu2020** [MarquezProject/marquez#821]
I follow the web that  https://marquezproject.github.io/marquez/quickstart.html ,

**[root@localhost marquez-0.11.2]# docker-compose up**

app_1  | ! Causing: org.flywaydb.core.internal.exception.FlywaySqlException:
app_1  | ! Unable to obtain connection from database: The connection attempt failed.
app_1  | ! -------------------------------------------------------------------------
app_1  | ! SQL State  : 08001
app_1  | ! Error Code : 0
**app_1  | ! Message    : The connection attempt failed.**

**[root@localhost marquez-0.11.2]# docker-compose ps**
       Name                     Command               State            Ports
-------------------------------------------------------------------------------------
marquez-0112_app_1   ./wait-for-it.sh db:5432 - ...   Exit 1
marquez-0112_db_1    docker-entrypoint.sh postgres    Up       0.0.0.0:5432->5432/tcp
**[root@localhost marquez-0.11.2]# docker-compose restart app**
Restarting marquez-0112_app_1 ... done
**[root@localhost marquez-0.11.2]# docker-compose ps**
       Name                     Command               State            Ports
-------------------------------------------------------------------------------------
marquez-0112_app_1   ./wait-for-it.sh db:5432 - ...   Exit 1
marquez-0112_db_1    docker-entrypoint.sh postgres    Up       0.0.0.0:5432->5432/tcp

**[root@localhost marquez-0.11.2]# docker-compose logs app**
app_1  | INFO  [2020-11-02 06:59:33,293] marquez.db.DbMigration: Repairing failed database migration...
app_1  | ERROR [2020-11-02 06:59:33,309] **org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.**
**app_1  | ! java.net.UnknownHostException: postgres**
app_1  | ! at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
.......
app_1  | ! **Unable to obtain connection from database: The connection attempt failed.**
app_1  | ! -------------------------------------------------------------------------
app_1  | ! SQL State  : 08001
app_1  | ! Error Code : 0
app_1  | ! Message    : The connection attempt failed.

But, I can connect the db by Navicat Premium , as follow:
![image](https://user-images.githubusercontent.com/72068448/97838646-9a00d380-1d1b-11eb-970a-d7b3e6f54504.png)

marquez-0112_app_1 exited with code 1
db_1   | 2020-11-02 07:22:27.738 UTC [74] ERROR:  **column c.relhasoids does not exist at character 190**
db_1   | 2020-11-02 07:22:27.738 UTC [74] STATEMENT:  SELECT c.oid, n.nspname AS schemaname, c.relname AS tablename, c.relacl, pg_get_userbyid(c.relowner) AS tableowner, obj_description(c.oid) AS description, c.relkind, ci.relname As cluster, c.relhasoids AS hasoids, c.relhasindex AS hasindexes, c.relhasrules AS hasrules, t.spcname AS tablespace, c.reloptions AS param, c.relhastriggers AS hastriggers, c.relpersistence AS unlogged, ft.ftoptions, fs.srvname, c.reltuples, ((SELECT count(*) FROM pg_inherits WHERE inhparent = c.oid) > 0) AS inhtable, i2.nspname AS inhschemaname, i2.relname AS inhtablename FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace LEFTJOIN pg_tablespace t ON t.oid = c.reltablespace LEFT JOIN (pg_inherits i INNER JOIN pg_class c2 ON i.inhparent = c2.oid LEFT JOIN pg_namespace n2 ON n2.oid = c2.relnamespace) i2 ON i2.inhrelid = c.oid LEFT JOIN pg_index ind ON(ind.indrelid = c.oid) and (ind.indisclustered = 't') LEFT JOIN pg_class ci ON ci.oid = ind.indexrelid LEFT JOIN pg_foreign_table ft ON ft.ftrelid = c.oid LEFT JOIN pg_foreign_server fs ON ft.ftserver = fs.oid WHERE ((c.relkind = 'r'::"char") OR (c.relkind = 'f'::"char")) AND n.nspname = 'public' ORDER BY schemaname, tablename

**How could I do ?**

**Comment by wslulciuc** [comment]
@HondaHsu2020 Thanks for opening this issue! The db connection is a docker compose related error. I just released [`0.11.3`](https://github.com/MarquezProject/marquez/releases/tag/0.11.3) with the fix. Mind trying `docker-compose up` and letting us know if that fixed your issue?

**Comment by wslulciuc** [comment]
@HondaHsu2020: I'm closing this issue for now (assuming it has been resolved). Please re-open if it's still a problem on your end and we'll be happy to help!
