### ISSUE TITLE
Marquez-web is using wrong port to talk with server

### ISSUE THREAD

**Issue by msilvestre** [MarquezProject/marquez#842]
Hi, my UI client is not reaching the server. It is trying to talk uisng port 3000 instead of 5000.

How can I configure it?

Thanks

<img width="1276" alt="Screenshot 2020-11-17 at 09 04 45" src="https://user-images.githubusercontent.com/16818020/99369253-1c5ccc00-28b4-11eb-834c-73a88204fc8c.png">

**Comment by wslulciuc** [comment]
@msilvestre: To help debug your issue, mind providing the steps used to bring up the marquez web and API?

**Comment by msilvestre** [comment]
Hi!

I just followed the steps provided here:
https://marquezproject.github.io/marquez/quickstart.html
* docker-compose up

And here:
https://github.com/MarquezProject/marquez/tree/main/web
* ./docker/up.sh

I have marquez running on port 5000 and manage to create the examples (namespace, source, dataset), and I have the WebUI running on port 3000 throwing the error above.

Thanks.

**Comment by wslulciuc** [comment]
Thanks for providing the steps for your setup. This is a common issue we see with

**Comment by wslulciuc** [comment]
Thanks for outlining the steps for your setup, @msilvestre! Yeah, this is a very common issue we see with newcomers of the project, and it's something we've been meaning to clarify. We've updated the [quickstart section](https://github.com/MarquezProject/marquez#quickstart) that will start both the web UI and server (and optionally seed API with metadata via a flag). Let us know if this fixes your setup :)

**Comment by msilvestre** [comment]
Thank you. It just worked.
