### ISSUE TITLE
Add tag creation API

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#854]
Currently, tags are defined using `config.yml`. But, it'd be helpful to also add support for creating a tag via an API call. For example:

### `POST` /api/v1/tags

```
{
  "name": STRING,
  "description": STRING
}
```

**Comment by hanbei** [comment]
Hey there, I created PR #1398 that tries to provide the endpoint. I decided to use PUT instead of POST as many other creation endpoints also use PUT. 
Not sure if I created/adapated all necessary tests / documentation. I would be glad about pointers to anything missing.

**Comment by wslulciuc** [comment]
Woah, thanks for the contribution @hanbei! We'll make sure to give your PR a review soon!

**Comment by julienledem** [comment]
resolved by #1398
