### ISSUE TITLE
Drop unique constraints (source, physical name) on datasets table

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#885]
We currently have two constraints on the `datasets` table:

```
(namespace_uuid, name)
(source_uuid, physical_name)
```

Let's avoid having both constraints and use the more natural constraints which is:

```
(namespace_uuid, name)
```

as a dataset must be unique within a namespace, but not across namespace. We can always enforce that a dataset does not already exits for a source in the API layer if needed.

**Comment by nizardeen** [comment]
I will work on this issue

**Comment by wslulciuc** [comment]
Thanks, @nizardeen! I just assigned the issue to you.

**Comment by julienledem** [comment]
This is now done
