### ISSUE TITLE
After update of Dataset it does not reflects on the UI

### ISSUE THREAD

**Issue by nizardeen** [MarquezProject/marquez#893]

**Comment by henneberger** [comment]
I think I can elaborate some. If a dataset exists when the dataset resource is called then the additional metadata is ignored. We introduced a new upsert mechanism in 2780a67445087 and we should migrate to the dataset service to use it. A prototype upsert mechanism for datasets was described in https://github.com/henneberger/marquez/blob/feature/openlineage/src/main/java/marquez/service/DatasetService.java if someone else wanted to take a lead at doing the migration. Let me know if I missed anything in describing this issue @nizardeen .

**Comment by julienledem** [comment]
@nizardeen This should be resolved now. Let us know if this is still an issue
