### ISSUE TITLE
Add open lineage facets to marquez rest api

### ISSUE THREAD

**Issue by henneberger** [MarquezProject/marquez#895]
This proposal adds open lineage facets to the marquez API for jobs, datasets, and runs. Additionally, this deprecates the context parameter and convert contexts to a special context facet. This will allow cross compatibility between the existing marquez apis and open lineage.

The scope of the api changes can be found: https://github.com/MarquezProject/marquez/pull/894

**Comment by wslulciuc** [comment]
Fixed #1261
